config/routes.rb
require 'sidekiq/web'
require_relative '../app/models/application_record'

Rails.application.routes.draw do
  get '/check.txt', to: proc { [200, {}, ['simple_check']] } # DOKKU DEPLOYMENT CHECK

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: 'pages#dashboard'
  # patch '/' => 'pages#dashboard'

  # Static Pages
  get 'help' => 'pages#help', as: 'help'
  get 'gs' => 'pages#google_slide'
  get 'gs/:slide_url' => 'pages#google_slide'

  # Mobile native for Control Plan
  get '/native/survey-questions' => 'native#survey_questions', as: 'survey_questions'
  get '/native/new-supplier' => 'native#new_supplier', as: 'new_supplier'
  get '/native/request_access' => 'native#request_access', as: 'request_access'
  get '/native/control_plan/index' => 'native#cp_index', as: 'cp_index'
  get '/native/control_plan/search' => 'native#cp_search', as: 'cp_search'
  get '/native/control_plan/product-list' => 'native#cp_product_list', as: 'cp_product_list'
  get '/native/control_plan/product' => 'native#cp_product', as: 'cp_product'
  get '/native/control_plan/product-design' => 'native#cp_product_design', as: 'cp_product_design'
  get '/native/control_plan/new-product' => 'native#cp_new_product', as: 'cp_new_product'
  get '/native/control_plan/schedule' => 'native#cp_schedule', as: 'cp_schedule'
  get '/native/control_plan/review' => 'native#cp_review', as: 'cp_review'
  get '/native/control_plan/review-detail' => 'native#cp_review_detail', as: 'cp_review_detail'
  get '/native/control_plan/findings' => 'native#cp_findings', as: 'cp_findings'
  get '/native/control_plan/history' => 'native#cp_history', as: 'cp_history'
  get '/native/control_plan/cphistory' => 'native#cp_cphistory', as: 'cp_cphistory'
  get '/native/control_plan/kpi' => 'native#cp_kpi', as: 'cp_kpi'
  get '/native/control_plan/list' => 'native#cp_list', as: 'cp_list'
  get '/native/control_plan/new-step' => 'native#cp_new_step', as: 'cp_new_step'
  get '/native/control_plan/report' => 'native#cp_report', as: 'cp_report'
  get '/native/cap/confirmation' => 'native#cap_confirmation', as: 'cap_confirmation'
  get '/native/cap/index' => 'native#cap_index', as: 'cap_index'
  get '/native/cap/form' => 'native#cap_form', as: 'cap_form'
  get '/native/cap/followup' => 'native#cap_followup', as: 'cap_followup'
  get '/native/cap/followup_invite' => 'native#cap_followup_invite', as: 'cap_followup_invite'
  get '/native/done' => 'native#done', as: 'done'

  #  Mobile native for assessor application

  get '/native/assessor_application/application' => 'native#aa_application', as: 'aa_application'
  get '/native/assessor_application/application_status' => 'native#aa_application_status', as: 'aa_application_status'
  get '/native/assessor_application/qualification' => 'native#aa_qualification', as: 'aa_qualification'
  get '/native/assessor_application/training_time' => 'native#aa_training_time', as: 'aa_training_time'
  get '/native/assessor_application/application_selection' => 'native#aa_application_selection', as: 'aa_application_selection'
  get '/native/assessor_application/validator' => 'native#aa_validator', as: 'aa_validator'
  get '/native/assessor_application/technical_eval' => 'native#aa_technical_eval', as: 'aa_technical_eval'

  # Mobile native for bug reporter
  get '/native/bug-tracker/form' => 'bugs#bug_tracker_form', as: 'bug_tracker_form'
  get '/native/bug-tracker/submitted' => 'bugs#bug_submitted', as: 'bug_submitted'
  # USERS CONTROLLER
  get 'users' => 'users#users', as: 'users'
  get 'users/staff' => 'users#staff', as: 'staff'
  get 'users/email_user' => 'users#email_user', as: 'email_user'
  post 'users/send_email' => 'users#send_email'
  get 'users/new' => 'users#users_new', as: 'users_new'
  get 'users/reset' => 'users#reset'
  get 'users/lock'  => 'users#lock'
  get 'users/unlock'  => 'users#unlock'
  get 'users/invite'  => 'users#invite'
  get 'users/permissions' => 'users#permissions'
  post 'users/permissions' => 'users#post_permissions'
  patch 'users/permissions' => 'users#patch_permissions'
  get 'users/permissions/all' => 'users#permissions_all'
  get 'users/test_login' => 'users#test_login'

  get 'suppliers'          => 'suppliers#suppliers', as: 'suppliers'
  get 'suppliers/:id/edit' => 'suppliers#suppliers_edit', as: 'suppliers_edit'
  get 'suppliers/new'      => 'suppliers#suppliers_new', as: 'suppliers_new'
  post 'add_supplier'      => 'suppliers#supplier_create'

  get 'locked' => 'users#locked', as: 'locked'
  # =====================================================
  # =====================================================

  # REPORTS
  get 'reports' => 'reports#reports', as: 'reports'
  get 'reports/my-reports' => 'reports#my_reports', as: 'my_reports'
  get 'reports/my-reports/:slug' => 'reports#update_report', as: 'update_report'
  get 'reports/my-reports/:slug/ap' => 'reports#update_ap', as: 'update_ap'
  get 'reports/my-reports/:slug/go' => 'reports#update_go', as: 'update_go'
  get 'reports/my-reports/:slug/ca' => 'reports#update_ca', as: 'update_ca'
  get 'reports/my-reports/:slug/cap' => 'reports#update_cap', as: 'update_cap'
  get 'reports/my-reports/:slug/finish' => 'reports#finish_qa', as: 'finish_qa'
  get 'reports/my-reports/:slug/comments' => 'reports#overall_comments', as: 'overall_comments'
  get 'reports/my-reports/:slug/ca/:chapter' => 'reports#update_chapter', as: 'update_chapter'
  get 'reports/my-reports/:slug/dormitory' => 'reports#update_dormitory', as: 'update_dormitory'
  get 'reports/my-reports/:slug/download' => 'reports#download', as: 'download_report'
  get 'reports/my-reports/:slug/download-excel' => 'reports#download_excel', as: 'download_excel'
  get 'reports/my-reports/:slug/download-cap-review' => 'reports#download_cap_review', as: 'download_cap_review'
  get 'reports/my-reports/:slug/upload-cap-revew' => 'reports#upload_cap_review', as: 'upload_cap_review'
  get 'reports/my-reports/:slug/generate-cap-revew' => 'reports#generate_cap_review', as: 'generate_cap_review'
  get 'reports/inprogress' => 'reports#inprogress', as: 'inprogress'
  get 'reports/completed' => 'reports#completed', as: 'completed'
  get 'reports/my-cp-reports/:slug' => 'reports#update_cp_report', as: 'update_cp_report'
  get 'reports/my-cp-reports/:slug/plan-item/:pi_id' => 'reports#update_plan_item', as: 'update_plan_item'
  get 'reports/my-cp-reports/:slug/download' => 'reports#download_cp', as: 'download_cp'

  # CONTROL PLAN
  get 'control-plan' => 'pages#control_plan', as: 'control_plan'
  get 'control-plan/:supplier_code/product-families' => 'control_plans#product_families', as: 'product_families'
  get 'control-plan/:supplier_code/product-families/:pf_id' => 'control_plans#update_product_family', as: 'update_product_family'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps' => 'control_plans#process_steps', as: 'process_steps'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps/:ps_id' => 'control_plans#update_process_step', as: 'update_process_step'

  # STATS
  get 'statistics' => 'statistics#statistics', as: 'stats'
  get 'statistics/excel-download' => 'statistics#excel_download', as: 'excel_download'
  get 'statistics/excel/supplier' => 'statistics#excel_by_code', as: 'excel_by_code'
  get 'statistics/excel/global' => 'statistics#excel_global', as: 'excel_global'
  get 'statistics/xuwei' => 'statistics#xuwei_stats'
  get 'statistics/country' => 'statistics#country', as: 'country_stats'
  get 'statistics/process' => 'statistics#industrial_process', as: 'process_stats'
  get 'statistics/result' => 'statistics#result', as: 'result_stats'
  get 'statistics/rank' => 'statistics#rank', as: 'rank_stats'
  get 'statistics/comment' => 'statistics#comment', as: 'comment_stats'
  get 'statistics/supplier' => 'statistics#supplier', as: 'supplier_stats'
  get 'statistics/supplier-full' => 'statistics#supplier_full', as: 'supplier_full_stats'
  get 'statistics/supplier/search' => 'statistics#supplier_search', as: 'supplier_stats_search'
  get 'statistics/supplier/history' => 'statistics#supplier_history', as: 'supplier_history_stats'
  get 'statistics/supplier/:supplier_code' => 'statistics#supplier_qa', as: 'supplier_qa_stats'
  get 'statistics/multiple-stats' => 'statistics#multiple_stats', as: 'multiple_stats'
  get 'statistics/assessment' => 'statistics#assessment', as: 'assessment_stats'

  get 'goes' => 'pages#goes', as: 'goes'

  # GUIDELINES
  get 'guidelines/show' => 'guidelines#show', as: 'guideline'
  get 'guidelines/prep' => 'guidelines#prep', as: 'guideline_prep'
  get 'guidelines/toolbox' => 'guidelines#toolbox', as: 'guideline_toolbox'
  get 'guidelines/frequency' => 'guidelines#frequency', as: 'guideline_frequency'
  post 'guidelines/frequency' => 'guidelines#frequency_update', as: 'create_guideline_frequency'
  post 'guidelines/frequency/:id' => 'guidelines#frequency_update', as: 'update_guideline_frequency'
  resources :guidelines, only: [:index, :edit, :update]

  # CP UPLOADER
  get  'upload-cp' => 'pages#upload_cp', as: 'upload_cp'
  post 'upload-cp' => 'pages#upload_cp', as: 'upload_cp_post'
  put  'upload-cp' => 'pages#upload_cp', as: 'upload_cp_put'

  get  'upload-historical-assessments' => 'pages#upload_historical_assessments', as: 'upload_historical_assessments_path'
  post 'upload-historical-assessments' => 'pages#upload_historical_assessments'
  # # ADMIN
  get 'new-change-log' => 'pages#new_change_log', as: 'change_log'

  get 'login' => 'pages#login', as: 'login'

  # EMAIL SYSTEM
  get 'email-system' => 'emails#email_system', as: 'email_system'
  get 'email-system/send-out' => 'emails#email_send_out', as: 'email_send_out'
  get 'email-system/send-out/new' => 'emails#letter_send_out_new', as: 'letter_send_out_new'
  post 'email-system/send-out/create' => 'emails#letter_send_out_create', as: 'letter_send_out_create'
  get 'email-system/send-out/show/:id' => 'emails#email_send_out_show', as: 'email_send_out_show'

app/views/native/_cp_index_card.html.erb
<%= link_to cp_review_path(cp_id: cp[:id]), class: 'no-underline color-free' do %>
    <article style="background: white; position: relative; margin-bottom: 25px; border-radius: 10px; padding: 16px" class="border-purple">
      <!-- <div class="assess-left border-purple" onclick="deleteCp(<%= cp[:id] %>)" style="z-index: 10">Delete</div> -->
      <div class="assess-right border-purple"><%= cp[:cpType][:desc] %></div>

      <div class="mb native-flex native-justify-between native-items-center">
        <div class="native-font-xs" style="background-color: <%= cp[:finished][:bgColor] %>; border-radius: 9999px; padding: 4px 8px; color: white;"><%= cp[:finished][:text] %></div>
        <div>
          <div class="native-dib native-font-sm light-gray">Supplier code</div>
          <div class="native-dib native-font-sm b"><%= cp[:supplier][:code] %></div>
        </div>
      </div>

      <div>
        <div class="native-flex native-items-start">
          <div style="width: 25%; background-color: #FCF3E5; border-radius: 4px; margin-right: 15px; text-align: center; padding-top: 10px;">
            <div class="native-font-sm" style="padding-bottom: 10px; border-bottom: 1px dashed #008EEF;"><%= cp[:review_month] %></div>
            <div style="background-color: #FCF3E5; text-align: center; font-weight: bold; padding: 10px 20px; margin-bottom: 10px;">
              <div style="background-color: white; padding: 10px 10px; border-radius:2px;"><%= cp[:review_day] %></div>
            </div>
          </div>
          <div class="native-font-sm" style="max-width: 70%;">
            <div>Supplier</div>
            <div class="native-content"><%= cp[:supplier][:name] %></div>
            <div>Product</div>
            <div class="native-content"><%= cp[:productFamily][:name] %></div>
          </div>
        </div>
      </div>
    </article>
    <% end %>

app/views/native/_divider.html.erb
<div class="wv-divider my">
  <div class="wv-divider-text"><%= txt %></div>
  <div class="wv-divider-line"></div>
</div>

app/views/native/_goback.html.erb
<% unless params[:key] %>
<div style="padding: 8px 0 8px 20px; color: white; background-color: #0198F1"><span onclick="goBack()"><%= render 'svg/goback' %><span style="display: inline-block; vertical-align: middle; font-weight: 800">Go Back</span></span></div>



<script>
  function goBack() {
    window.history.back();
  }
</script>
<% end %>

app/views/native/cp_product.html.erb
<% tt = 'api.v1.control_plan.product' %>
<%= render 'goback' %>

<div class="main-content-wrapper">
  <!-- start header -->
  <div class="native-font-lg b mb"><%= @supplier.name%></div>

  <!-- end header -->
  <!-- card start -->
  <%= render 'product_show_card', pf: @product_family %>
  <!-- card end -->
  <!-- active links -->
  <div class="native-flex native-items-center native-justify-between mb">
    <div class="native-font-sm b"><%= t(tt+'.change_history')%></div>
    <% if @h[:recentUpdates].length > 0 %>
    <button class="btn-primary-blue native-font-xs" style="color: white" onclick="goHistory(<%= @product_family.id %>)"><%= t(tt+'.view_change_btn')%></button>
    <% end %>
  </div>
  <div class="native-flex native-items-center native-justify-between mb">
    <div class="native-font-sm b"><%= t(tt+'.cp_history')%></div>
    <% if @h[:recentUpdates].length > 0 %>
    <button class="btn-primary-blue native-font-xs" style="color: white" onclick="goCPHistory(<%= @product_family.id %>)"><%= t(tt+'.view_cp_history_btn')%></button>
    <% end %>
  </div>
  <!-- active links -->
  <!-- start recent updates -->
  <% if @h[:recentUpdates].length > 0 %>
  <div class="bg-lightgray pa mb">
    <% @h[:recentUpdates].each_with_index do |item, index| %>
      <% if @h[:recentUpdates][index - 1][:date] != item[:date] %>
        <div class="b native-font-sm mb-10"><%= item[:date]%></div>
      <% end %>
        <div><span class="b"><%= item[:event] %>:</span>  <%= item[:abbr_name] %></div>
    <% end %>
  </div>
  <% else %>
  <div class="my"><%= t(tt+'.update_na')%></div>
  <% end %>
  <!-- end recent updates -->
  <!-- supplier flow images -->
  <div class="b mb native-font-sm"><%= t(tt+'.supplier_process_flow')%></div>
  <div class="native-flex native-flex-wrap">
    <% @h[:productFamily][:images].each_with_index do |img, index|%>
    <div class="native-thumbnail mr mb-10" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= img %>');">
      <!-- <button class="native-delete-thumbnail">X</button> -->
    </div>
    <% end %>

  </div>
  <!-- end supplier flow images -->
  <!-- production control plan -->
  <div class="native-flex native-items-center native-justify-between mb">
    <div class="b native-font-sm"><%= t(tt+'.prod_cp')%></div>
    <%= link_to cp_list_path(id: @product_family.id) do %>
    <button class="btn-primary-blue native-font-xs" style="color: white" onclick="goSteps()"><%= t(tt+'.view_edit_btn')%></button>
    <% end %>
  </div>

  <div class="border-purple" style="background: white; position: relative; margin-bottom: 25px; border-radius: 10px; padding: 16px">
    <div class="native-flex native-items-center native-justify-between">
      <div>
        <div class="steps-result" style="color: gray"><%= @h[:pcpSteps][:available] %></div>
        <div class="native-font-sm">Steps Available</div>
      </div>
      <div>
        <div class="steps-result" style="color: dodgerblue"><%= @h[:pcpSteps][:reviewed] %></div>
        <div class="native-font-sm">Steps Reviewed</div>
      </div>
      <div>
        <div class="steps-result" style="color: darkred"><%= @h[:pcpSteps][:pending] %></div>
        <div class="native-font-sm">Steps Pending</div>
      </div>
    </div>
  </div>
  <!-- end production control plan -->
  <!-- start schedule review -->
  <div class="native-flex native-items-center native-justify-between mb">
    <div class="b native-font-sm"><%= t(tt+'.schedule_review')%></div>
    <button onclick="goSchedule()" class="btn-primary-blue native-font-xs" style="color: white"><%= t(tt+'.schedule_date_btn')%></button>
  </div>
  <% if @h[:scheduleReview].present?%>
    <%= render "schedule_cp_card", c: @h[:scheduleReview] %>
  <% else %>
    <div class="tc my"><%= t(tt+'.no_schedule')%></div>
  <% end %>
  <!-- end schedule review -->
  <!-- start kpi -->
  <!-- <div class="native-flex native-items-center native-justify-between mb">
    <div class="b native-font-sm"><%= t(tt+'.kpi_rate')%></div>
    <button class="btn-primary-blue native-font-xs" style="color: white" onclick="goKpi()"><%= t(tt+'.view_kpi_btn')%></button>
  </div> -->
  <%#= render 'kpi_card', c: @h[:kpiCard]  %>
  <!-- end kpi -->
</div>
<%= render 'native/shared/floating' %>
<script>
  function goHistory(id){
    Turbolinks.visit(`<%= cp_history_path(product_id: @product_family.id) %>`)
  }
  function goCPHistory(id){
    Turbolinks.visit(`<%= cp_cphistory_path(product_family_id: @product_family.id) %>`)
  }
  function goSchedule(id){
    Turbolinks.visit(`<%= cp_schedule_path(id: @product_family.id) %>`)
  }
</script>

app/views/native/cp_schedule.html.erb
<% tt = 'api.v1.control_plan.schedule' %>
<%= render 'goback' %>
<script src="/vendor/list.js"></script>
<div class="main-content-wrapper">
  <div class="native-font-lg b mb-5"><%= t(tt+'.title')%></div>
  <div class="native-font-sm b"><%= t(tt+'.find_supplier')%></div>

  <!-- Input with autocomplete -->
  <div id="hacker-list" class="my" style="width: 100%;">
    <input type="text" id="autocomplete-input" class="search native-input border-purple" onkeyup="showList()" style="background: white" placeholder="Search supplier code or name..." value="<%= @supplier.name if params[:supplier_id] %>" />
    <!-- Autocomplete list is hidden, to show remove class -->
    <div id="ac-list" class="native-hidden" style="position: relative; height: 8em; width: inherit; overflow: scroll; z-index: 527">
      <div class="">
        <ul class="list bg-white">
          <% SupplierProfile.source_list.each do |s| %>
          <a class="no-underline" href="?supplier_id=<%= s[:id] %>">
            <li class="auto-list-item native-font-sm" ><span class="code"><%= s[:code] %></span> <span class="name"><%= s[:name] %></span></li>
          </a>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!-- End input with autocomplete -->

  <% if @supplier.present? %>
  <section>
    <!-- Suppler information card -->
    <article id="" class="border-blue" style="background: white; position: relative; margin-bottom: 25px; border-radius: 10px; padding: 16px">
      <div class="native-flex native-justify-end mb">
        <div>
          <div class="native-dib native-font-sm light-gray">Supplier code</div>
          <div class="native-dib native-font-sm b"><%= @supplier.code %></div>
        </div>
      </div>
      <div class="native-font-sm">
        <div>Supplier name</div>
        <div class="native-content" style="width: inherit;"><%= @supplier.name %></div>
        <div>Address</div>
        <div class="native-content" style="width: inherit;"><%= @supplier.city %>, <%= @supplier.country %></div>
        <div>Contact name</div>
        <div class="native-content" style="width: inherit;"><%= @supplier.contact_name %></div>
        <div>Contact email</div>
        <div class="native-content" style="width: inherit;"><%= @supplier.contact_email %></div>
      </div>
    </article>
    <!-- End supplier information card -->

    <% if  @supplier.product_families.where(destroyed_at: nil).blank? %>
    <div class="my">
      <div class="native-font-sm b" style="color: dodgerblue; text-align: center;">There are no products for this supplier!</div>
      <div class="my">
        <%= link_to cp_new_product_path(id: @supplier.id) do %>
          <button class="btn-primary" style="font-size: 1em; width: 100%;">Add Product</button>
        <% end %>
      </div>
    </div>
    <!-- End if no products -->
    <% else %>
    <!-- If have products -->

    <%= form_with model: ControlPlan.new, url: api_v1_members_control_plan_schedule_path do |f| %>
    <div class="my">
      <!-- Start product selection -->
      <div class="my">
        <div class="native-label"><%= t(tt+'.choose_product')%></div>
        <div class="mb" style="position: relative">
          <select id="products" name="products" class="native-select" onchange="Turbolinks.visit('?product_id='+this.value)">
            <% @supplier.product_families.where(destroyed_at: nil).each do |k| %>
            <option value="<%= k.id %>" <%= 'selected' if @product_family.id == k.id %>><%= k.name %></option>
            <% end %>
          </select>
          <div style="position: absolute; bottom: 5px; right: 5px; pointer: none; padding: 5px;">
             <svg style="height: 15px; width: 15px; fill-color: black;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
          </div>
        </div>
        <input type="hidden" name="product_family_id" value="<%= @product_family.id || @supplier.product_families.where(destroyed_at: nil).first.id %>">
        <div class="native-label"><%= t(tt+'.cp_monitor_date')%></div>
        <div class="mb" style="position: relative">
          <input type="date" class="native-date" name="supplier_schedule_date" required="true">
        </div>
        <div class="native-label"><%= t(tt+'.select_review')%></div>
        <div class="mb" style="position: relative">
          <div class="native-font-sm mb-10" id="explainers"></div>
          <select id="review_type" name="cp_type" class="native-select" onchange="updateExplainers(this.value)" >
            <option selected style="color: gainsboro !important">Select one</option>
            <option value="New Monitor">New Monitor</option>
            <option value="CAP Review">Cap Review</option>
          </select>
          <div style="position: absolute; bottom: 5px; right: 5px; pointer: none; padding: 5px;">
             <svg style="height: 15px; width: 15px; fill-color: black;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
          </div>
        </div>
      </div>
      <!-- End product selection -->

      <!-- Start divider -->

      <% if @h[:productProcesses].values.reject(&:blank?).present? %>
      <div class="my">
        <div class="wv-divider">
          <div class="wv-divider-text native-font-sm"><%= t(tt+'.select_steps')%></div>
          <div class="wv-divider-line"></div>
        </div>
      </div>
      <% else %>
        <div class="my" style="margin-top: 60px;">
          <div style="text-align: center;"> <%= t(tt+'.no_steps') %> </div>
        </div>

        <!-- <div class="my" style="margin-top: 30px; margin-bottom: 60px;">
          <a href="<%= cp_new_step_path(product_family_id: @product_family.id || @supplier.product_families.where(destroyed_at: nil).first.id ) %>" class="btn-primary" style="width: 100%; font-size: 1em; display: block;text-align: center;"><%= t(tt+'.add_btn') %></a>
        </div> -->
      <% end %>
      <!-- End divider -->

      <% @h[:process_categories].each do |key_name| %>
      <% next if @h[:productProcesses][key_name].blank? %>
      <section class="my">
        <article class="border-purple native-font-sm" style="background: white; margin-bottom: 25px; border-radius: 10px">
          <div class="b pa"><%= key_name %></div>
          <% @h[:productProcesses][key_name].each do |process| %>
            <% next if process[:steps].blank? %>

            <div class="py bg-lightgray">
              <div class="native-flex native-justify-between pa">
                <div class="b" style="width: 80%; padding-right: 10px; line-height: 1.2"><%= process[:name] %></div>
                <!-- <div>
                  <button class="btn-primary-blue native-font-sm" style="padding: 5px; color: white;">Check all</button>
                </div> -->
              </div>
            </div>
            <!-- Checkboxes -->
            <div class="pa">
              <% process[:steps].each_with_index do |step, i| %>
              <div class="native-flex native-items-start mb">
                <input class="native-checkbox mr" type="checkbox" id="item_<%= step[:id] %>" name="item_ids[]id" value="<%= step[:id] %>" onchange="validateSubmit()">
                <div for="item<%= step[:id] %>">
                  <div class="b mb-10"><%=step[:step_number]%> <%=step[:control_item]%>:</div>
                  <div style="line-height: 1.2"><%=step[:control_method]%></div>
                </div>
              </div>
              <% end %>
            </div>
          <% end %>
          <!-- End Checkboxes -->
        </article>
      </section>
      <% end %>
      <div class="my">
        <%= f.submit "Submit Date Review →", class: "btn-primary", style: "width: 100%; font-size: 1em; display: none;", id: "submit_btn" %>
      </div>

      <!-- End steps to monitor -->
    </div>
    <% end %>
    <!-- End if have products -->
    <% end %>
  </section>
  <% end %>
</div>



<script>
  var explainers = <%= raw t(tt+'.explainers').to_json %>;
  var options = {
    valueNames: [ 'name', 'code' ]
  };
  var hackerList = new List('hacker-list', options);

  function validateSubmit(){
    var counter = 0
    document.querySelectorAll('input[name="item_ids[]id"]').forEach(
      function(item){if (item.checked){counter += 1 }})
    var submit = document.getElementById('submit_btn')

    if (counter > 0){
      submit.style.display = "block"
    } else {
      submit.style.display = "none"
    }

  }

  function showList(){
    var autocomplete = document.getElementById('autocomplete-input')
    autocomplete.addEventListener("input", function(e) {
      var list = document.getElementById('ac-list')
      if (autocomplete.value.length > 0){
        list.classList.remove("native-hidden")
      } else {
        list.classList.add("native-hidden")
      }
    });
  }

  function updateExplainers(value){
    document.getElementById('explainers').innerText = explainers[value]
  }
var form = document.querySelector('form')
  form.addEventListener('ajax:success', function(){
    window.location = "/native/done?text=<%= CGI.escape('Control Plan is now scheduled.') %>";
  })
</script>