config/routes.rb
require 'sidekiq/web'
require_relative '../app/models/application_record'

Rails.application.routes.draw do
  get '/check.txt', to: proc { [200, {}, ['simple_check']] } # DOKKU DEPLOYMENT CHECK

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: 'pages#dashboard'
  # patch '/' => 'pages#dashboard'

  # Static Pages
  get 'help' => 'pages#help', as: 'help'
  get 'gs' => 'pages#google_slide'
  get 'gs/:slide_url' => 'pages#google_slide'

  # Mobile native for Control Plan
  get '/native/survey-questions' => 'native#survey_questions', as: 'survey_questions'
  get '/native/new-supplier' => 'native#new_supplier', as: 'new_supplier'
  get '/native/request_access' => 'native#request_access', as: 'request_access'
  get '/native/control_plan/index' => 'native#cp_index', as: 'cp_index'
  get '/native/control_plan/search' => 'native#cp_search', as: 'cp_search'
  get '/native/control_plan/product-list' => 'native#cp_product_list', as: 'cp_product_list'
  get '/native/control_plan/product' => 'native#cp_product', as: 'cp_product'
  get '/native/control_plan/product-design' => 'native#cp_product_design', as: 'cp_product_design'
  get '/native/control_plan/new-product' => 'native#cp_new_product', as: 'cp_new_product'
  get '/native/control_plan/schedule' => 'native#cp_schedule', as: 'cp_schedule'
  get '/native/control_plan/review' => 'native#cp_review', as: 'cp_review'
  get '/native/control_plan/review-detail' => 'native#cp_review_detail', as: 'cp_review_detail'
  get '/native/control_plan/findings' => 'native#cp_findings', as: 'cp_findings'
  get '/native/control_plan/history' => 'native#cp_history', as: 'cp_history'
  get '/native/control_plan/cphistory' => 'native#cp_cphistory', as: 'cp_cphistory'
  get '/native/control_plan/kpi' => 'native#cp_kpi', as: 'cp_kpi'
  get '/native/control_plan/list' => 'native#cp_list', as: 'cp_list'
  get '/native/control_plan/new-step' => 'native#cp_new_step', as: 'cp_new_step'
  get '/native/control_plan/report' => 'native#cp_report', as: 'cp_report'
  get '/native/cap/confirmation' => 'native#cap_confirmation', as: 'cap_confirmation'
  get '/native/cap/index' => 'native#cap_index', as: 'cap_index'
  get '/native/cap/form' => 'native#cap_form', as: 'cap_form'
  get '/native/cap/followup' => 'native#cap_followup', as: 'cap_followup'
  get '/native/cap/followup_invite' => 'native#cap_followup_invite', as: 'cap_followup_invite'
  get '/native/done' => 'native#done', as: 'done'

  #  Mobile native for assessor application

  get '/native/assessor_application/application' => 'native#aa_application', as: 'aa_application'
  get '/native/assessor_application/application_status' => 'native#aa_application_status', as: 'aa_application_status'
  get '/native/assessor_application/qualification' => 'native#aa_qualification', as: 'aa_qualification'
  get '/native/assessor_application/training_time' => 'native#aa_training_time', as: 'aa_training_time'
  get '/native/assessor_application/application_selection' => 'native#aa_application_selection', as: 'aa_application_selection'
  get '/native/assessor_application/validator' => 'native#aa_validator', as: 'aa_validator'
  get '/native/assessor_application/technical_eval' => 'native#aa_technical_eval', as: 'aa_technical_eval'

  # Mobile native for bug reporter
  get '/native/bug-tracker/form' => 'bugs#bug_tracker_form', as: 'bug_tracker_form'
  get '/native/bug-tracker/submitted' => 'bugs#bug_submitted', as: 'bug_submitted'
  # USERS CONTROLLER
  get 'users' => 'users#users', as: 'users'
  get 'users/staff' => 'users#staff', as: 'staff'
  get 'users/email_user' => 'users#email_user', as: 'email_user'
  post 'users/send_email' => 'users#send_email'
  get 'users/new' => 'users#users_new', as: 'users_new'
  get 'users/reset' => 'users#reset'
  get 'users/lock'  => 'users#lock'
  get 'users/unlock'  => 'users#unlock'
  get 'users/invite'  => 'users#invite'
  get 'users/permissions' => 'users#permissions'
  post 'users/permissions' => 'users#post_permissions'
  patch 'users/permissions' => 'users#patch_permissions'
  get 'users/permissions/all' => 'users#permissions_all'
  get 'users/test_login' => 'users#test_login'

  get 'suppliers'          => 'suppliers#suppliers', as: 'suppliers'
  get 'suppliers/:id/edit' => 'suppliers#suppliers_edit', as: 'suppliers_edit'
  get 'suppliers/new'      => 'suppliers#suppliers_new', as: 'suppliers_new'
  post 'add_supplier'      => 'suppliers#supplier_create'

  get 'locked' => 'users#locked', as: 'locked'
  # =====================================================
  # =====================================================

  # REPORTS
  get 'reports' => 'reports#reports', as: 'reports'
  get 'reports/my-reports' => 'reports#my_reports', as: 'my_reports'
  get 'reports/my-reports/:slug' => 'reports#update_report', as: 'update_report'
  get 'reports/my-reports/:slug/ap' => 'reports#update_ap', as: 'update_ap'
  get 'reports/my-reports/:slug/go' => 'reports#update_go', as: 'update_go'
  get 'reports/my-reports/:slug/ca' => 'reports#update_ca', as: 'update_ca'
  get 'reports/my-reports/:slug/cap' => 'reports#update_cap', as: 'update_cap'
  get 'reports/my-reports/:slug/finish' => 'reports#finish_qa', as: 'finish_qa'
  get 'reports/my-reports/:slug/comments' => 'reports#overall_comments', as: 'overall_comments'
  get 'reports/my-reports/:slug/ca/:chapter' => 'reports#update_chapter', as: 'update_chapter'
  get 'reports/my-reports/:slug/dormitory' => 'reports#update_dormitory', as: 'update_dormitory'
  get 'reports/my-reports/:slug/download' => 'reports#download', as: 'download_report'
  get 'reports/my-reports/:slug/download-excel' => 'reports#download_excel', as: 'download_excel'
  get 'reports/my-reports/:slug/download-cap-review' => 'reports#download_cap_review', as: 'download_cap_review'
  get 'reports/my-reports/:slug/upload-cap-revew' => 'reports#upload_cap_review', as: 'upload_cap_review'
  get 'reports/my-reports/:slug/generate-cap-revew' => 'reports#generate_cap_review', as: 'generate_cap_review'
  get 'reports/inprogress' => 'reports#inprogress', as: 'inprogress'
  get 'reports/completed' => 'reports#completed', as: 'completed'
  get 'reports/my-cp-reports/:slug' => 'reports#update_cp_report', as: 'update_cp_report'
  get 'reports/my-cp-reports/:slug/plan-item/:pi_id' => 'reports#update_plan_item', as: 'update_plan_item'
  get 'reports/my-cp-reports/:slug/download' => 'reports#download_cp', as: 'download_cp'

  # CONTROL PLAN
  get 'control-plan' => 'pages#control_plan', as: 'control_plan'
  get 'control-plan/:supplier_code/product-families' => 'control_plans#product_families', as: 'product_families'
  get 'control-plan/:supplier_code/product-families/:pf_id' => 'control_plans#update_product_family', as: 'update_product_family'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps' => 'control_plans#process_steps', as: 'process_steps'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps/:ps_id' => 'control_plans#update_process_step', as: 'update_process_step'

  # STATS
  get 'statistics' => 'statistics#statistics', as: 'stats'
  get 'statistics/excel-download' => 'statistics#excel_download', as: 'excel_download'
  get 'statistics/excel/supplier' => 'statistics#excel_by_code', as: 'excel_by_code'
  get 'statistics/excel/global' => 'statistics#excel_global', as: 'excel_global'
  get 'statistics/xuwei' => 'statistics#xuwei_stats'
  get 'statistics/country' => 'statistics#country', as: 'country_stats'
  get 'statistics/process' => 'statistics#industrial_process', as: 'process_stats'
  get 'statistics/result' => 'statistics#result', as: 'result_stats'
  get 'statistics/rank' => 'statistics#rank', as: 'rank_stats'
  get 'statistics/comment' => 'statistics#comment', as: 'comment_stats'
  get 'statistics/supplier' => 'statistics#supplier', as: 'supplier_stats'
  get 'statistics/supplier-full' => 'statistics#supplier_full', as: 'supplier_full_stats'
  get 'statistics/supplier/search' => 'statistics#supplier_search', as: 'supplier_stats_search'
  get 'statistics/supplier/history' => 'statistics#supplier_history', as: 'supplier_history_stats'
  get 'statistics/supplier/:supplier_code' => 'statistics#supplier_qa', as: 'supplier_qa_stats'
  get 'statistics/multiple-stats' => 'statistics#multiple_stats', as: 'multiple_stats'
  get 'statistics/assessment' => 'statistics#assessment', as: 'assessment_stats'

  get 'goes' => 'pages#goes', as: 'goes'

  # GUIDELINES
  get 'guidelines/show' => 'guidelines#show', as: 'guideline'
  get 'guidelines/prep' => 'guidelines#prep', as: 'guideline_prep'
  get 'guidelines/toolbox' => 'guidelines#toolbox', as: 'guideline_toolbox'
  get 'guidelines/frequency' => 'guidelines#frequency', as: 'guideline_frequency'
  post 'guidelines/frequency' => 'guidelines#frequency_update', as: 'create_guideline_frequency'
  post 'guidelines/frequency/:id' => 'guidelines#frequency_update', as: 'update_guideline_frequency'
  resources :guidelines, only: [:index, :edit, :update]

  # CP UPLOADER
  get  'upload-cp' => 'pages#upload_cp', as: 'upload_cp'
  post 'upload-cp' => 'pages#upload_cp', as: 'upload_cp_post'
  put  'upload-cp' => 'pages#upload_cp', as: 'upload_cp_put'

  get  'upload-historical-assessments' => 'pages#upload_historical_assessments', as: 'upload_historical_assessments_path'
  post 'upload-historical-assessments' => 'pages#upload_historical_assessments'
  # # ADMIN
  get 'new-change-log' => 'pages#new_change_log', as: 'change_log'

  get 'login' => 'pages#login', as: 'login'

  # EMAIL SYSTEM
  get 'email-system' => 'emails#email_system', as: 'email_system'
  get 'email-system/send-out' => 'emails#email_send_out', as: 'email_send_out'
  get 'email-system/send-out/new' => 'emails#letter_send_out_new', as: 'letter_send_out_new'
  post 'email-system/send-out/create' => 'emails#letter_send_out_create', as: 'letter_send_out_create'
  get 'email-system/send-out/show/:id' => 'emails#email_send_out_show', as: 'email_send_out_show'

app/models/users/authentication_token.rb
class AuthenticationToken < ApplicationRecord
  belongs_to :user
  has_paper_trail ignore: %i[created_at updated_at]

  include MessageScheduler
end

app/controllers/users_controller.rb
require 'creek'
class UsersController < BaseController
  def users
    @active = 'users'
  end

  def staff
    if params[:id].present?
      setup_qr(:user)
    else
      @active = 'users'
      users = User.includes(:assessor_profile, :authentication_tokens)
                  .where('username NOT LIKE ?', '%@%').where.not(assessor_profiles: { id: nil, name: nil })
                  .order(created_at: :desc).map(&:assessor_profile)
      @staff = users
      @qa_uids = AssessorAssignment.select(:user_id).all.distinct.map(&:user_id)
      @cps_uids = ControlPlan.select(:created_by).where(destroyed_at: nil).distinct.map(&:created_by)
    end
  end

  def email_user
    @assessors = User.includes(:assessor_profile, :authentication_tokens).where.not(email: '',
                                                                                    assessor_profiles: { id: nil,
                                                                                                         name: nil }).order(created_at: :desc).select do |x|
      x.assessor_profile.assessor_for.present?
    end
    @suppliers = SupplierProfile.includes(:user,
                                          user: :authentication_tokens).where.not(user_id: nil).order(created_at: :desc).map(&:user).select do |u|
      !u.email.empty?
    end
    @emails_filter = SupplierProfile.all.map { |x| { label: "#{x.name} Assessment", value: x.cpm } }
    @decathlonians = User.includes(:assessor_profile, :authentication_tokens).where('email ILIKE ?',
                                                                                    '%@decathlon%').where.not(assessor_profiles: {
                                                                                                                id: nil, name: nil
                                                                                                              })
    @grid_leaders = User.includes(:assessor_profile, :authentication_tokens).where('email ILIKE ?',
                                                                                   '%@decathlon%').where.not(assessor_profiles: {
                                                                                                               id: nil, name: nil
                                                                                                             }).select do |x|
      x.access_levels.include?('grid') || x.access_levels.include?('grids') || x.access_levels.include?('guidelines')
    end
  end

  def send_email
    users = params[:users]
    email_template = params[:email_template]
    users.each do |u|
      User.find(u).send_mail!(email_template)
    end
    redirect_to email_user_path
  end

  def permissions; end

  def post_permissions
    u_params = params.require(:user).permit(:file, access_levels: [])
    @file = u_params[:file]
    creek = Creek::Book.new(@file.tempfile)
    sheet = creek.sheets.first
    sheet.rows_with_meta_data.each do |row|
      full_cells = row['cells'].reject { |_k, v| v.nil? }
      next if full_cells.blank?

      profile = full_cells.values.first
      next if profile == 'profile'

      u = User.find_for_authentication(username: profile)
      next if u.blank?

      u.access_levels += u_params[:access_levels]
      u.access_levels.uniq!
      u.save
    end
    redirect_to staff_path
  end

  def permissions_all
    base = User.includes(:assessor_profile, :supplier_profile)
    @users = case params[:type]
             when 'supplier'
               base.where.not(supplier_id: nil).or(base.where.not({ supplier_profiles: { id: nil } }))
             when 'assessor'
               base.where.not(assessor_profiles: { assessor_for: [] })
             when 'grid_leader'
               base.where("'guidelines' = ANY (users.access_levels)")
             else
               base.all
             end
  end

  def patch_permissions
    u = User.find_by(id: params[:user_id])
    u_params = params.require(:user).permit(access_levels: [],
                                            assessor_profile_attributes: [:id, :user_id,
                                                                          { assessor_for: [], referent_for: [] }])
    p u_params
    u.update(u_params)
    redirect_to staff_path
  end

  def locked
    @active = 'users'
    @users = User.includes(:assessor_profile, :supplier_profile, :supplier).where.not(locked_at: nil)
  end

  # ===============================
  # SWAL CONFIRMED ACTIONS
  # ===============================
  def reset
    @user = User.find_by_username(params[:username])
    pass = 'Decathlon' # SecureRandom.urlsafe_base64(4).upcase
    @user.password = pass
    if @user.save
      render json: { msg: "New password for #{params[:username]} is <span style='color:red'>#{pass}</span>" }
    else
      render json: { msg: 'Password Update Failed' }
    end
  end

  def lock
    @user = User.find_by_username(params[:username])
    @user.locked_at = Time.now
    if @user.save
      render json: { msg: "<span style='color:red'>#{params[:username]}</span> Account Locked!" }
    else
      render json: { msg: 'Account Lock Failed' }
    end
  end

  def unlock
    @user = User.find_by_username(params[:username])
    @user.locked_at = nil
    if @user.save
      render json: { msg: "<span style='color:red'>#{params[:username]}</span> Account Unlocked!" }
    else
      render json: { msg: 'Account Unlock Failed' }
    end
  end

  def invite
    @user = User.find_by_username(params[:username])
    @supplier = @user.supplier || @user.supplier_profile

    if @supplier.present?
      @user.send_mail!('welcome')
      if @supplier.update invite_sent_at: Time.now
        render json: { msg: "Invitation sent to #{params[:username]} - #{@supplier.name}" }
      else
        render json: { msg: 'Sending Invitation Failed' }
      end
    end
  end

  def test_login
    puts "testing login\n\n\n\n#{params}"
    email_found = User.find_by(email: params['email'])
    puts "email found? #{email_found}"
    valid_password = email_found.valid_password?(params['password']) unless email_found.nil?
    puts "password valid? #{valid_password}"

    if email_found.nil?
      render json: { msg: 'User not found' }
    elsif !valid_password
      render json: { msg: 'Password incorrect' }
    else
      render json: { msg: 'This account is valid' }
    end
  end

  private

  def setup_qr(type)
    qr = {
      user: { page: 'members/show/show', scene: "id=#{params[:id]}" },
      supplier: { page: 'members/show/show', scene: "supplierid=#{params[:id]}" }
    }

    h = qr[type]
    render json: WxAuthentication.mp_qrcode(h)
  end

  def permission_scope
    current_user.can_manage?('users')
  end
end

app/views/users/_email_form.html.erb
<%= form_with url: "send_email", method: :post, class: "w-50" do |f| %>

<% users = params[:users] || [] %>

  <label style="font-size: 0.8em;" for="">Recipients</label><br>

      <!-- ASSESSORS -->
  <select name="users[]" selected="users" id="email_<%= form_type %>s" multiple="multiple" placeholder="Search <%= form_type.humanize %>">
    <% user_list.each do |u| %>
      <option <%= users.include?(u) ? 'selected' : '' %> value="<%= u.id %>"><%= u.profile.name %></option>
    <% end %>
  </select>

  <label style="font-size: 0.8em; margin-top: 24px;" for="">Email Template</label><br>

  <!-- ASSESSORS -->
  <select class="choices__inner" name="email_template" id="email_template" placeholder="Select email template">
    <option value="">Select email template</option>
    <% templates.each do |value, label| %>
      <option value="<%= value %>"><%= label %></option>
    <% end %>
  </select>

  <input style="margin-top: 3em;" name="commit" type="submit" value="Send mail" class="btn btn-xs" style="width: 35%; box-shadow: none; outline: none;">

<% end %>

app/views/users/email_user.html.erb
<div class='wrapper'  style="margin-bottom: 1rem;position: relative;">
  <div style="margin-bottom: 1rem;"><a href="/users">Users</a> › Email User </div>
</div>

<div style="margin: 10px 0 20px;">
  <label for="input_text" style=" margin-bottom: 0.8rem;">Select recipient type</label><br>

  <input type="radio" name="user_type" id="user_type_assessor" style="box-shadow: none; width: auto;" checked onclick="toggleRecipients('a')">
  <label for="user_type_assessor">Assessor</label>

  <input type="radio" name="user_type" id="user_type_decathlonian" style="box-shadow: none; width: auto;" onclick="toggleRecipients('d')">
  <label for="user_type_decathlonian">Decathlonian</label>

  <input type="radio" name="user_type" id="user_type_grid_leader" style="box-shadow: none; width: auto;" onclick="toggleRecipients('gl')">
  <label for="user_type_grid_leader">Grid Leader</label>

  <input type="radio" name="user_type" id="user_type_supplier" style="box-shadow: none; width: auto;" onclick="toggleRecipients('s')">
  <label for="user_type_supplier">Supplier</label>
</div>

<div id="assessor_form">
  <%= render "email_form", user_list: @assessors, templates: User::EMAIL_ASSESSOR_TEMPLATES, form_type: 'assessor' %>
</div>

<div id="decathlonian_form">
  <%= render "email_form", user_list: @assessors, templates: User::EMAIL_ASSESSOR_TEMPLATES, form_type: 'decathlonian' %>
</div>

<div id="grid_leaders_form">
  <%= render "email_form", user_list: @assessors, templates: User::EMAIL_ASSESSOR_TEMPLATES, form_type: 'grid_leader' %>
</div>

<div id="supplier_form">
  <%= render "email_form", user_list: @suppliers, templates: User::EMAIL_SUPPLIER_TEMPLATES, form_type: 'supplier' %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", statsFilterChoices())

  var ass = document.getElementById('assessor_form')
  var sup = document.getElementById('supplier_form')
  var dec = document.getElementById('decathlonian_form')
  var gl = document.getElementById('grid_leaders_form')

  document.addEventListener("turbolinks:load", () => { dec.style.display = 'none' })
  document.addEventListener("turbolinks:load", () => { gl.style.display = 'none' })
  document.addEventListener("turbolinks:load", () => { sup.style.display = 'none' })

  var toggleRecipients = (e) => {
    ass.style.display = e == 'a' ? 'block' : 'none'
    sup.style.display = e == 's' ? 'block' : 'none'
    dec.style.display = e == 'd' ? 'block' : 'none'
    gl.style.display = e == 'gl' ? 'block' : 'none'
  }
</script>

app/views/users/permissions.html.erb
<div class='wrapper'  style="margin-bottom: 1rem;position: relative;">
  <div style="margin-bottom: 1rem;"><%= link_to users_path, class: 'underline blue hover-gray' do %>Users<% end %> › <%= link_to staff_path, class: 'underline blue hover-gray' do %>Staff<% end %> › Permissions</div>
</div>

<% permissions = [['users', 'Can Manage Users'], ['my-reports', 'Can Edit Own Reports'], ['all-reports', 'Can View All Reports'],['guidelines', 'Can Edit Grids'], ["suppliers", 'Can Manage Suppliers']] %>

<% grids = QualityAssessment::ACTIVE_GRIDS %>

<% if params[:user_id] %>
  <%= form_with model: User.find(params[:user_id]), url: users_permissions_path, local: true do |f| %>
    <input type="hidden" name="user_id" value="<%= params[:user_id] %>">
    <p>Which features would you like to grant permission?</p>
    <% permissions.each do |x| %>
      <div>
        <%= f.check_box :access_levels, {multiple: true, id: x[0]}, x[0], nil%>
        <label for="<%= x[0] %>"><%= x[1] %></label>
      </div>
    <% end %>

    <%= f.fields_for :assessor_profile do |j| %>
      <%= j.hidden_field :user_id, value: params[:user_id] %>
      <input type="hidden" name="user_id" value="<%= params[:user_id] %>">
      <p style="margin-top: 10px;">Which grid would you like to set as Assessor?</p>
      <% grids.each do |g| %>
        <div>
          <%= j.check_box :assessor_for, {multiple: true, id: "assessor-for-#{g}"}, g, nil%>
          <label for="<%= g %>"><%= g %></label>
        </div>
      <% end %>
      <p style="margin-top: 10px;">Which grid would you like to set as Referent?</p>
      <% grids.each do |g| %>
        <div>
          <%= j.check_box :referent_for, {multiple: true, id: "assessor-for-#{g}"}, g, nil%>
          <label for="<%= g %>"><%= g %></label>
        </div>
      <% end %>
    <% end %>
    <%= f.submit "Submit", class: "btn-md no-shadow", style: "line-height: 1; margin: 1rem 0;" %>
  <% end %>
<% else %>
  <%= form_with model: User.new, url: users_permissions_path, local: true do |f| %>
    <div style="margin: 1rem 0;">
      <label for="attach">Attach the excel file of users</label>
      <br>
      <%= f.file_field :file, accept: XFile::XLSX %>
    </div>

    <p>Please check which users you would like to grant permission </p>

    <% permissions.each do |x| %>
    <div>
      <input type="checkbox" id="<%= x[0] %>" name="user[access_levels][]" value="<%= x[0] %>">
      <label for="<%= x[0] %>"><%= x[1] %></label>
    </div>
    <% end %>

    <%= f.submit "Submit", class: "btn-md no-shadow", style: "line-height: 1; margin: 1rem 0;" %>

  <% end %>
<% end %>

app/views/users/staff.html.erb
<div class='wrapper'  style="margin-bottom: 1rem;position: relative;">
  <div style="margin-bottom: 1rem;"><a href="/users">Users</a> › Staff </div>
  <div style="display: flex; justify-content: space-between; align-items: center;">
  <h4>Staff Accounts <a href="<%= users_permissions_path %>"><small>bulk edit permissions</small></a></h4>
  </div>
</div>

<% permissions = {'users' => 'Can Manage Users', 'my-reports' => 'Can Edit Own Reports', 'all-reports' => 'Can View All Reports','guidelines' => 'Can Edit Grids', "suppliers" => 'Can Manage Suppliers'} %>

<div id="table-scroll" class="table-scroll">
  <table id="main-table" class="main-table">
    <thead>
      <tr>
        <th scope="col" style="width: 50px"></th>
        <th scope="col" style="width: 100px;">Profile <span><%= render 'svg/direction' %></span></th>
        <th scope="col" style="width: 250px;">Name <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Last login <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Access levels <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Actions <span><%= render 'svg/direction' %></span></th>
      </tr>
    </thead>
    <tbody>
      <% @staff.each_with_index do |s, i| %>
      <tr>
        <th><%= i+1 %></th>
        <th><%= s.handle %></th>
        <th><%= s.name %>
          <% if s.user.present? && s.user.locked_at.present? %>
            <span class="br-pill btn-xs" style="background: darkred; color: white; display: inline-block;padding: 0px 6px; border-radius: 10px">LOCKED</span>
          <% end %>

        </th>
        <td style="font-size: 1.1rem">
          <div>
          <% if s.user.blank? %>
          User Account <%= s.handle %> has no active user account
          <% elsif login = s.last_login %>
          <%= login.strftime("%Y-%m-%d") %>
          <% elsif login.nil? %>
          User Account <%= s.handle %> has not Used the WeChat MP
          <% end %>
          </div>
          <% if s.user && s.user.last_oa_invite %>
            <div class="bg-blue pa2 white" style="border-radius: 50%; width: 15px; height: 15px; padding: 3px; display: flex; justify-content: center; align-items: center; margin-right: 5px;">OA Invite Sent</div>
          <% end %>
        </td>
        <td style="font-size: 1.1rem">
          <% access_levels = s.user.access_levels %>
          <% if access_levels.present? %>
            <%= raw access_levels.map{|x| permissions[x]}.reject(&:nil?).join("<br>") %>
          <% end %>
        </td>
        <td>
          <a onclick="getQrcode('<%= s.id %>', '<%= s.name %>');" class="btn-xs">View on mini program</a>
          <% if s.user.present? && s.user.locked_at.nil?  %>
          <a onclick="verifyUsername('<%= s.user.username %>', 'lock')" class="btn-xs">Lock Account</a>
          <% elsif s.user.present? && s.user.locked_at.present? %>
          <a onclick="verifyUsername('<%= s.user.username %>', 'unlock')" class="btn-xs">Unlock Account</a>
          <% end %>
          <a href="<%= users_permissions_path(user_id: s.user_id) %>" class="btn-xs">Edit Permissions</a>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div style="width: 100%; background: #32A2ED; height: 4rem; border-bottom-right-radius:40px; border-bottom-left-radius:40px; color: white;">
  <div style="display: flex; justify-content: space-between; padding: 1rem 1.1rem;">
    <div>Total users: <strong><%= @staff.count %></strong></div>
    <div>Passive users (logged on before): <strong><%= @staff.select{|x| x.user.authentication_tokens.present?}.count %></strong></div>
    <div>Active users (assessed before): <strong><%= @staff.select{|x| @qa_uids.include?(x.user_id) || @cps_uids.include?(x.user_id)}.count %></strong></div>
  </div>
</div>

<%= javascript_include_tag "table_filter.js" %>