config/routes.rb
require 'sidekiq/web'
require_relative '../app/models/application_record'

Rails.application.routes.draw do
  get '/check.txt', to: proc { [200, {}, ['simple_check']] } # DOKKU DEPLOYMENT CHECK

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: 'pages#dashboard'
  # patch '/' => 'pages#dashboard'

  # Static Pages
  get 'help' => 'pages#help', as: 'help'
  get 'gs' => 'pages#google_slide'
  get 'gs/:slide_url' => 'pages#google_slide'

  # Mobile native for Control Plan
  get '/native/survey-questions' => 'native#survey_questions', as: 'survey_questions'
  get '/native/new-supplier' => 'native#new_supplier', as: 'new_supplier'
  get '/native/request_access' => 'native#request_access', as: 'request_access'
  get '/native/control_plan/index' => 'native#cp_index', as: 'cp_index'
  get '/native/control_plan/search' => 'native#cp_search', as: 'cp_search'
  get '/native/control_plan/product-list' => 'native#cp_product_list', as: 'cp_product_list'
  get '/native/control_plan/product' => 'native#cp_product', as: 'cp_product'
  get '/native/control_plan/product-design' => 'native#cp_product_design', as: 'cp_product_design'
  get '/native/control_plan/new-product' => 'native#cp_new_product', as: 'cp_new_product'
  get '/native/control_plan/schedule' => 'native#cp_schedule', as: 'cp_schedule'
  get '/native/control_plan/review' => 'native#cp_review', as: 'cp_review'
  get '/native/control_plan/review-detail' => 'native#cp_review_detail', as: 'cp_review_detail'
  get '/native/control_plan/findings' => 'native#cp_findings', as: 'cp_findings'
  get '/native/control_plan/history' => 'native#cp_history', as: 'cp_history'
  get '/native/control_plan/cphistory' => 'native#cp_cphistory', as: 'cp_cphistory'
  get '/native/control_plan/kpi' => 'native#cp_kpi', as: 'cp_kpi'
  get '/native/control_plan/list' => 'native#cp_list', as: 'cp_list'
  get '/native/control_plan/new-step' => 'native#cp_new_step', as: 'cp_new_step'
  get '/native/control_plan/report' => 'native#cp_report', as: 'cp_report'
  get '/native/cap/confirmation' => 'native#cap_confirmation', as: 'cap_confirmation'
  get '/native/cap/index' => 'native#cap_index', as: 'cap_index'
  get '/native/cap/form' => 'native#cap_form', as: 'cap_form'
  get '/native/cap/followup' => 'native#cap_followup', as: 'cap_followup'
  get '/native/cap/followup_invite' => 'native#cap_followup_invite', as: 'cap_followup_invite'
  get '/native/done' => 'native#done', as: 'done'

  #  Mobile native for assessor application

  get '/native/assessor_application/application' => 'native#aa_application', as: 'aa_application'
  get '/native/assessor_application/application_status' => 'native#aa_application_status', as: 'aa_application_status'
  get '/native/assessor_application/qualification' => 'native#aa_qualification', as: 'aa_qualification'
  get '/native/assessor_application/training_time' => 'native#aa_training_time', as: 'aa_training_time'
  get '/native/assessor_application/application_selection' => 'native#aa_application_selection', as: 'aa_application_selection'
  get '/native/assessor_application/validator' => 'native#aa_validator', as: 'aa_validator'
  get '/native/assessor_application/technical_eval' => 'native#aa_technical_eval', as: 'aa_technical_eval'

  # Mobile native for bug reporter
  get '/native/bug-tracker/form' => 'bugs#bug_tracker_form', as: 'bug_tracker_form'
  get '/native/bug-tracker/submitted' => 'bugs#bug_submitted', as: 'bug_submitted'
  # USERS CONTROLLER
  get 'users' => 'users#users', as: 'users'
  get 'users/staff' => 'users#staff', as: 'staff'
  get 'users/email_user' => 'users#email_user', as: 'email_user'
  post 'users/send_email' => 'users#send_email'
  get 'users/new' => 'users#users_new', as: 'users_new'
  get 'users/reset' => 'users#reset'
  get 'users/lock'  => 'users#lock'
  get 'users/unlock'  => 'users#unlock'
  get 'users/invite'  => 'users#invite'
  get 'users/permissions' => 'users#permissions'
  post 'users/permissions' => 'users#post_permissions'
  patch 'users/permissions' => 'users#patch_permissions'
  get 'users/permissions/all' => 'users#permissions_all'
  get 'users/test_login' => 'users#test_login'

  get 'suppliers'          => 'suppliers#suppliers', as: 'suppliers'
  get 'suppliers/:id/edit' => 'suppliers#suppliers_edit', as: 'suppliers_edit'
  get 'suppliers/new'      => 'suppliers#suppliers_new', as: 'suppliers_new'
  post 'add_supplier'      => 'suppliers#supplier_create'

  get 'locked' => 'users#locked', as: 'locked'
  # =====================================================
  # =====================================================

  # REPORTS
  get 'reports' => 'reports#reports', as: 'reports'
  get 'reports/my-reports' => 'reports#my_reports', as: 'my_reports'
  get 'reports/my-reports/:slug' => 'reports#update_report', as: 'update_report'
  get 'reports/my-reports/:slug/ap' => 'reports#update_ap', as: 'update_ap'
  get 'reports/my-reports/:slug/go' => 'reports#update_go', as: 'update_go'
  get 'reports/my-reports/:slug/ca' => 'reports#update_ca', as: 'update_ca'
  get 'reports/my-reports/:slug/cap' => 'reports#update_cap', as: 'update_cap'
  get 'reports/my-reports/:slug/finish' => 'reports#finish_qa', as: 'finish_qa'
  get 'reports/my-reports/:slug/comments' => 'reports#overall_comments', as: 'overall_comments'
  get 'reports/my-reports/:slug/ca/:chapter' => 'reports#update_chapter', as: 'update_chapter'
  get 'reports/my-reports/:slug/dormitory' => 'reports#update_dormitory', as: 'update_dormitory'
  get 'reports/my-reports/:slug/download' => 'reports#download', as: 'download_report'
  get 'reports/my-reports/:slug/download-excel' => 'reports#download_excel', as: 'download_excel'
  get 'reports/my-reports/:slug/download-cap-review' => 'reports#download_cap_review', as: 'download_cap_review'
  get 'reports/my-reports/:slug/upload-cap-revew' => 'reports#upload_cap_review', as: 'upload_cap_review'
  get 'reports/my-reports/:slug/generate-cap-revew' => 'reports#generate_cap_review', as: 'generate_cap_review'
  get 'reports/inprogress' => 'reports#inprogress', as: 'inprogress'
  get 'reports/completed' => 'reports#completed', as: 'completed'
  get 'reports/my-cp-reports/:slug' => 'reports#update_cp_report', as: 'update_cp_report'
  get 'reports/my-cp-reports/:slug/plan-item/:pi_id' => 'reports#update_plan_item', as: 'update_plan_item'
  get 'reports/my-cp-reports/:slug/download' => 'reports#download_cp', as: 'download_cp'

  # CONTROL PLAN
  get 'control-plan' => 'pages#control_plan', as: 'control_plan'
  get 'control-plan/:supplier_code/product-families' => 'control_plans#product_families', as: 'product_families'
  get 'control-plan/:supplier_code/product-families/:pf_id' => 'control_plans#update_product_family', as: 'update_product_family'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps' => 'control_plans#process_steps', as: 'process_steps'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps/:ps_id' => 'control_plans#update_process_step', as: 'update_process_step'

  # STATS
  get 'statistics' => 'statistics#statistics', as: 'stats'
  get 'statistics/excel-download' => 'statistics#excel_download', as: 'excel_download'
  get 'statistics/excel/supplier' => 'statistics#excel_by_code', as: 'excel_by_code'
  get 'statistics/excel/global' => 'statistics#excel_global', as: 'excel_global'
  get 'statistics/xuwei' => 'statistics#xuwei_stats'
  get 'statistics/country' => 'statistics#country', as: 'country_stats'
  get 'statistics/process' => 'statistics#industrial_process', as: 'process_stats'
  get 'statistics/result' => 'statistics#result', as: 'result_stats'
  get 'statistics/rank' => 'statistics#rank', as: 'rank_stats'
  get 'statistics/comment' => 'statistics#comment', as: 'comment_stats'
  get 'statistics/supplier' => 'statistics#supplier', as: 'supplier_stats'
  get 'statistics/supplier-full' => 'statistics#supplier_full', as: 'supplier_full_stats'
  get 'statistics/supplier/search' => 'statistics#supplier_search', as: 'supplier_stats_search'
  get 'statistics/supplier/history' => 'statistics#supplier_history', as: 'supplier_history_stats'
  get 'statistics/supplier/:supplier_code' => 'statistics#supplier_qa', as: 'supplier_qa_stats'
  get 'statistics/multiple-stats' => 'statistics#multiple_stats', as: 'multiple_stats'
  get 'statistics/assessment' => 'statistics#assessment', as: 'assessment_stats'

  get 'goes' => 'pages#goes', as: 'goes'

  # GUIDELINES
  get 'guidelines/show' => 'guidelines#show', as: 'guideline'
  get 'guidelines/prep' => 'guidelines#prep', as: 'guideline_prep'
  get 'guidelines/toolbox' => 'guidelines#toolbox', as: 'guideline_toolbox'
  get 'guidelines/frequency' => 'guidelines#frequency', as: 'guideline_frequency'
  post 'guidelines/frequency' => 'guidelines#frequency_update', as: 'create_guideline_frequency'
  post 'guidelines/frequency/:id' => 'guidelines#frequency_update', as: 'update_guideline_frequency'
  resources :guidelines, only: [:index, :edit, :update]

  # CP UPLOADER
  get  'upload-cp' => 'pages#upload_cp', as: 'upload_cp'
  post 'upload-cp' => 'pages#upload_cp', as: 'upload_cp_post'
  put  'upload-cp' => 'pages#upload_cp', as: 'upload_cp_put'

  get  'upload-historical-assessments' => 'pages#upload_historical_assessments', as: 'upload_historical_assessments_path'
  post 'upload-historical-assessments' => 'pages#upload_historical_assessments'
  # # ADMIN
  get 'new-change-log' => 'pages#new_change_log', as: 'change_log'

  get 'login' => 'pages#login', as: 'login'

  # EMAIL SYSTEM
  get 'email-system' => 'emails#email_system', as: 'email_system'
  get 'email-system/send-out' => 'emails#email_send_out', as: 'email_send_out'
  get 'email-system/send-out/new' => 'emails#letter_send_out_new', as: 'letter_send_out_new'
  post 'email-system/send-out/create' => 'emails#letter_send_out_create', as: 'letter_send_out_create'
  get 'email-system/send-out/show/:id' => 'emails#email_send_out_show', as: 'email_send_out_show'

app/models/control_plans/control_plan.rb
class ControlPlan < ApplicationRecord
  attr_reader :show_sections, :sections, :color, :cap_closed, :short_name,
              :grid, :previous_score, :official_assessment

  belongs_to :product_family
  belongs_to :assessor_profile, optional: true
  belongs_to :cap, optional: true
  belongs_to :user, class_name: 'User', foreign_key: 'created_by', optional: true

  has_many :plan_items, dependent: :destroy
  has_many :goes_activities, -> { where(ref_model: 'control_plan') }, foreign_key: 'ref_id'
  has_many :likes, -> { where(ref_model: 'control_plan') }, foreign_key: 'ref_id'
  has_many :favorites, -> { where(ref_model: 'control_plan') }, foreign_key: 'ref_id'

  has_one :schedule, foreign_key: 'ref_id'
  has_one_attached :report
  has_paper_trail ignore: %i[created_at updated_at]
  scope :active, -> { where(destroyed_at: nil) }
  scope :destroyed, -> { where.not(destroyed_at: nil) }
  scope :complete, -> { where(completed: true) }
  scope :include_supplier, -> { includes(product_family: :supplier_profile) }
  scope :include_assessor, -> { includes(:assessor_profile).where(assessor_type: 'assessor') }

  # ASSESS_TYPE = ['Fundamental', 'Advanced', 'CAP Review']
  ASSESS_TYPE = ['New Monitor', 'CAP Review', 'Implementation Order']
  # CONTROL_TYPES = ["Records & Method Control", "Process Control", "Product Control", "Visual/Cosmetic Control", "Lab Control"]
  include MessageScheduler
  include ControlPlanHelper::People
  include ControlPlanHelper::Relations
  include ControlPlanHelper::Radars
  include ControlPlanHelper::Utils
  include ControlPlanHelper::Calculations
  include ControlPlanHelper::Forms
  include ControlPlanHelper::Reports

  validates_uniqueness_of :slug
  before_create :generate_slug
  after_initialize :set_static_vars
  alias cap_closed? cap_closed
  alias cap_close? cap_closed
  alias official_assessment? official_assessment
  alias show_sections? show_sections
  alias creator user

  def supplier_users
    supplier_profile.users.map { |x| { id: "s#{x.id}", name: x.username } }
  end

  def set_static_vars
    @official_assessment = true
    @show_sections = false
    @sections = ''
    @color = '#A147C5'
    @cap_closed = false
    @short_name = 'CP'
    @grid = 'control_plan'
    @previous_score = nil
  end

  def can_edit?(_uid)
    true
  end

  def render_activity(user)
    goes_params = super
    goes_params[:ref_type] = plan_type
    # ONLY ON CREATE AND COMPLETE

    if completed?
      goes_params[:ref_status] = 'CP Monitor Completed!'
      goes_params[:content] =
        "#{user.name.split(' ').first.capitalize} has finished a Control Plan Monitor! Take a look and offer some helpful advice"
      GoesActivity.create(goes_params)
    elsif updated_at == created_at
      goes_params[:ref_status] = "CP #{plan_type} Scheduled!"
      goes_params[:content] = "#{user.name.split(' ').first.capitalize} has scheduled a new CP!"
      GoesActivity.create(goes_params)
    end
  end

  def to_h
    h = serializable_hash.transform_keys!(&:to_sym)
    h[:assess_date] = assess_date.strftime('%Y-%m-%d')
    h
  end
end

app/models/control_plans/control_plan_helper/calculations.rb
module ControlPlanHelper::Calculations
  extend ActiveSupport::Concern

  def stats
    [
      { label: 'Nonconformity Rate', value: nonconformity_rate },
      { label: 'Frequency Respect Rate', value: freq_respect_rate },
      { label: 'CAP Close Rate', value: cap_close_rate }
    ]
  end

  def nonconformity_rate
    return 0 if plan_items.blank?

    pi = plan_items
    (pi.select { |x| x.result == 'NOK' }.count.to_f / pi.length * 100).round(2)
  end

  def freq_respect_rate(freq_for = 'Decathlon', fresh_query = true)
    return 100 if plan_items.blank?

    ps = plan_items.map(&:process_step).flatten.map { |x| x.freq_respected?(freq_for, fresh_query) }.flatten
    return 100 if ps.blank?

    (ps.select { |x| x == true }.count.to_f * 100 / ps.count).round(0)
  end

  def cap_close_rate
    return 100 if plan_items.blank?

    caps = plan_items.map(&:cap_points).flatten.map { |x| x.resolved_at.present? }
    # TODO: getting an error here that prevents some execution, not sure if this is the right way of handling it or not
    return 0 if caps.blank?

    (caps.select { |x| x == true }.count.to_f * 100 / caps.count).round(0)
  end

  def cap_finished?
    cap_points.where(resolved_at: nil).blank?
  end
end

app/models/control_plans/control_plan_helper/forms.rb
module ControlPlanHelper::Forms
  extend ActiveSupport::Concern

  def generate_cap_prep
    pis = plan_items.where(result: 'NOK')
    h = {}
    h[:ref_model] = 'control_plan'
    h[:ref_id] = id
    # h[:cap_date] ASKED IN FORM
    # h[:cap_type] ASKED IN FORM
    h[:supplier_profile_id] = product_family.supplier_profile_id
    # h[:pl_id] ASK DURING CP?
    h[:points] = []
    h[:recheck] = []
    pis.each do |pi|
      process_step = pi.process_step
      new_h = {}
      new_h[:ref_model] = 'plan_item'
      new_h[:ref_id]    = pi.id
      new_h[:section]   = process_step.product_process.name
      new_h[:level]     = process_step.step_number
      new_h[:requirement] = "#{process_step.requirement}\n Frequency: #{process_step.decathlon_control_freq}"
      new_h[:result]    = pi.result || 'N/A'
      new_h[:bullets]   = ["Findings: #{pi.findings}", "Immediate Actions/Protections: #{pi.actions}"]

      if pi.block
        h[:recheck] << new_h
      else
        h[:points] << new_h
      end
    end
    h
  end
end

app/models/control_plans/control_plan_helper/relations.rb
module ControlPlanHelper::Relations
  extend ActiveSupport::Concern
  def schedule
    Schedule.find_by(ref_id: id)
  end

  def process_steps
    ProcessStep.includes(:plan_items).includes(plan_items: :control_plan)
               .where(control_plans: { id: id })
  end

  def steps_available
    plan_items.select { |x| x.active }
  end

  def steps_reviewed
    steps_available.select { |x| x.completed }
  end

  def steps_pending
    steps_available.reject { |x| x.completed }
  end

  def cap_points
    process_step_ids = process_steps.map { |x| x.id }
    CapPoint.includes(:cap).joins('INNER JOIN "plan_items" ON "plan_items"."id" = "cap_points"."ref_id"')
            .where(cap_points: { ref_model: 'plan_item' },
                   plan_items: { process_step_id: process_step_ids })
            .where(caps: { completed: false })
  end

  def related_caps
    return Cap.where(ref_model: 'control_plan', ref_id: cap.ref_id) if cap_id.present?

    []
  end

  def caps
    Cap.where(ref_model: 'control_plan', ref_id: id)
  end
end

app/models/control_plans/cp_pending_frequency.rb
class CpPendingFrequency < ApplicationRecord
  belongs_to :process_step
  has_paper_trail ignore: %i[created_at updated_at]

  def complete!
    update(resolved_at: Time.now)
    x = eval(process_step.decathlon_control_freq) || 2.weeks
    CpPendingFrequency.create(process_step_id: process_step_id, frequency_for: frequency_for, expires_at: Time.now + x)
  end
end

app/models/control_plans/kpi_record.rb
class KpiRecord < ApplicationRecord
  belongs_to :kpi_track
  validates :value, presence: true
  has_paper_trail ignore: %i[created_at updated_at]
end

app/controllers/control_plans_controller.rb
class ControlPlansController < BaseController
  before_action :set_supplier
  before_action :set_pf

  def product_families
    @product_families = @supplier.product_families.where(destroyed_at: nil)
  end

  def update_product_family; end

  def process_steps
    @steps = @pf.process_steps.where(destroyed_at: nil).order(:step_number)
  end

  def update_process_step
    @steps = @pf.process_steps.where(destroyed_at: nil)
    @step = @steps.find(params[:ps_id])
  end

  private

  def set_supplier
    @supplier = SupplierProfile.find_by(code: params[:supplier_code])
  end

  def set_pf
    @pf = ProductFamily.find_by(id: params[:pf_id])
  end

  def permission_scope
    true
  end
end

app/views/control_plans/process_steps.html.erb
<div class='wrapper' style="margin-bottom: 0.5rem">
  <div style="margin-bottom: 1rem;"><a href="/control-plan">Control Plans</a> › <%= @supplier.name %> › <%= link_to product_families_path do %>Product Families<% end %> › Process Steps for <%= @pf.name %></div>
</div>

<div class="wrapper">
  <h3>Process Steps for <%= @pf.name %></h3>
</div>

<div id="table-scroll" class="table-scroll" style="margin-bottom: 2rem;">
  <table id="main-table" class="main-table">
    <thead>
      <tr>
        <th scope="col">Step Number</th>
        <th scope="col">What to Control</th>
        <th scope="col">Product Process Category</th>
        <th scope="col">Process</th>
        <th scope="col">Step</th>
      </tr>
    </thead>
    <tbody>
      <% @steps.each_with_index do |s, i| %>
      <tr>
        <th><%= s.step_number %></th>
        <td><%= s.control_item %></td>
        <td><%= s.product_process.category %></td>
        <td><%= s.product_process.name %></td>
        <td>
          <%= link_to update_process_step_path(ps_id: s.id), class: 'no-underline' do %><button class="btn-xs">Edit Process</button><% end %>

          <%= link_to "/api/v1/process_steps/#{s.id}", method: :delete, data: {turbolinks: false, confirm: "Are you sure you want to delete this step?"}, remote: true, class: 'no-underline' do %><button class="btn-xs">Delete Process</button><% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  var remote_links = document.querySelectorAll('a[data-remote=true]');

  remote_links.forEach(function(inputElm){
    inputElm.addEventListener('ajax:complete', function(event){
      Turbolinks.visit(window.location.path)
    });
  })
</script>

app/views/control_plans/product_families.html.erb
<div class='wrapper' style="margin-bottom: 0.5rem">
  <div style="margin-bottom: 1rem;"><a href="/control-plan">Control Plans</a> › <%= @supplier.name %> › Product Families </div>
</div>

<div class="b"><%= @supplier.name %></div>
<p style="margin-bottom: 2rem;">Last updated: <span><%= @supplier.updated_at.strftime("%Y-%m-%d") %></span></p>

<div class="wrapper">
  <h3>Product Families</h3>
</div>

<div id="table-scroll" class="table-scroll">
  <table id="main-table" class="main-table" style="min-width:fit-content;">
    <thead>
      <tr>
        <th scope="col">Product</th>
        <th scope="col">Steps Count</th>
        <th scope="col">Last Update</th>
        <th scope="col">Product Info</th>

      </tr>
    </thead>
    <tbody>
      <% @product_families.each do |product| %>
      <tr>
        <th><%= product.name %></th>
        <th><%= product.process_steps.count %></th>
        <td style="font-size: 1.1rem"><%= product.updated_at.strftime("%Y-%m-%d") %></td>
        <td>
          <%= link_to update_product_family_path(pf_id: product.id), class: 'no-underline' do %>
            <button class="btn-xs">Edit Product Family</button>
          <% end %>
          <%= link_to process_steps_path(pf_id: product.id) do %>
            <button class="btn-xs">Process Steps</button>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div style="width: 100%; background: #32A2ED; height: 4rem; border-bottom-right-radius:40px; border-bottom-left-radius:40px; color: white;">
  <div style="display: flex; justify-content: space-between; padding: 1rem 1.1rem;">
    <div>Total Products: <strong><%= @product_families.count %></strong></div>
    <div></div>
    <div></div>
  </div>
</div>

app/views/control_plans/update_product_family.html.erb
<div class='wrapper' style="margin-bottom: 0.5rem">
  <div style="margin-bottom: 1rem;"><a href="/control-plan">Control Plans</a> › <%= @supplier.name %> › <%= link_to product_families_path do %>Product Families<% end %> › Editing <%= @pf.name %>  </div>
</div>


<%= form_with model: @pf, method: :post, url: "/api/v1/product_families/#{@pf.id}" do |f| %>
  <div style="margin: 10px 0;">
    <label for="input_text" style=" margin-bottom: 0.8rem;">Title</label>
    <br>
    <%= f.text_field :name, class: "w-50" %>
  </div>
  <div style="margin: 10px 0;">
    <label for="input_text" style=" margin-bottom: 0.8rem;">Current Level</label>
    <br>
    <%= f.text_field :current_level, class: "w-50" %>
  </div>
  <div style="margin: 10px 0;">
    <label for="input_text" style=" margin-bottom: 0.8rem;">Target Level</label>
    <br>
    <%= f.text_field :target_level, class: "w-50" %>
  </div>

  <div style="margin: 10px 0;">
    <label for="input_text" style=" margin-bottom: 0.8rem;">Upload Process flow Image</label>
    <br>
    <%= f.file_field :process_flow_images, multiple: true, accept: XFile::COMMON, style: "width: 30%", direct_upload: true, onchange:"autoClickForm(event.target.form);" %>
  </div>
  <% @pf.process_flow_images.each_with_index do |x, i| %>
  <% album = @pf.process_flow_images.map{|x| rails_blob_path(x)} %>
    <div style="position: relative; display: inline-block; width: 100px; height: 100px; margin: 1em 1em 1em 0;">
      <a class="bg-blue white b id-<%= @pf.id %>" style="border-bottom: 1px solid rgba(183, 221, 247, 1.00); line-height: 1.2; position: absolute; top: -9px; right: -9px; border-radius: 50%; width: 15px; height: 15px; padding: 3px; font-size: 0.6em; text-align: center;" data-index="<%= i %>" onclick="deleteImage(this, 'product_families', 'process_flow_images', <%= @pf.id %>, this.dataset.index )" >✖︎</a>
      <img src="<%= rails_blob_path(x) %>" alt="" height="100px" width="100px" style="object-fit: cover;" onclick="launchLightbox(this)" data-id="<%= @pf.id %>-i<%= i %>" data-album="<%= album.join(':::') %>">
    </div>
  <% end %>
  <div style="margin: 10px 0;">
    <%= f.submit "Update Product Information", class: "btn-md w-50", style: "display: inline-block; margin-right: 15px;" %>
  </div>
<% end %>



<script>

  function launchLightbox(e) {

      var album = e.getAttribute("data-album")
      var body = document.querySelector('body')
      var div = document.createElement('div')
      var id = e.getAttribute("data-id")
      div.id = id
      body.appendChild(div)
      console.log(id, 'here')
      console.log(e)
      // console.log(album, '---------------------')
      var res = album.split(":::").map(function(x){return {"src": x , "thumb": x, "subHtml": ''}})
      console.log(res)
      // console.log(res)
      var active = document.getElementById(id)

      lightGallery(active, {
          dynamic: true,
          dynamicEl: res,
          download: false
      })
  }


  var form = document.querySelector('form')
  form.addEventListener('ajax:success', function(){
    window.location = `<%= request.protocol %><%= request.host %><%= request.port == 80 ? '' : ":#{request.port}" %>/control-plan/<%= @supplier.code %>/product-families`
  })

</script>