config/routes.rb
require 'sidekiq/web'
require_relative '../app/models/application_record'

Rails.application.routes.draw do
  get '/check.txt', to: proc { [200, {}, ['simple_check']] } # DOKKU DEPLOYMENT CHECK

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: 'pages#dashboard'
  # patch '/' => 'pages#dashboard'

  # Static Pages
  get 'help' => 'pages#help', as: 'help'
  get 'gs' => 'pages#google_slide'
  get 'gs/:slide_url' => 'pages#google_slide'

  # Mobile native for Control Plan
  get '/native/survey-questions' => 'native#survey_questions', as: 'survey_questions'
  get '/native/new-supplier' => 'native#new_supplier', as: 'new_supplier'
  get '/native/request_access' => 'native#request_access', as: 'request_access'
  get '/native/control_plan/index' => 'native#cp_index', as: 'cp_index'
  get '/native/control_plan/search' => 'native#cp_search', as: 'cp_search'
  get '/native/control_plan/product-list' => 'native#cp_product_list', as: 'cp_product_list'
  get '/native/control_plan/product' => 'native#cp_product', as: 'cp_product'
  get '/native/control_plan/product-design' => 'native#cp_product_design', as: 'cp_product_design'
  get '/native/control_plan/new-product' => 'native#cp_new_product', as: 'cp_new_product'
  get '/native/control_plan/schedule' => 'native#cp_schedule', as: 'cp_schedule'
  get '/native/control_plan/review' => 'native#cp_review', as: 'cp_review'
  get '/native/control_plan/review-detail' => 'native#cp_review_detail', as: 'cp_review_detail'
  get '/native/control_plan/findings' => 'native#cp_findings', as: 'cp_findings'
  get '/native/control_plan/history' => 'native#cp_history', as: 'cp_history'
  get '/native/control_plan/cphistory' => 'native#cp_cphistory', as: 'cp_cphistory'
  get '/native/control_plan/kpi' => 'native#cp_kpi', as: 'cp_kpi'
  get '/native/control_plan/list' => 'native#cp_list', as: 'cp_list'
  get '/native/control_plan/new-step' => 'native#cp_new_step', as: 'cp_new_step'
  get '/native/control_plan/report' => 'native#cp_report', as: 'cp_report'
  get '/native/cap/confirmation' => 'native#cap_confirmation', as: 'cap_confirmation'
  get '/native/cap/index' => 'native#cap_index', as: 'cap_index'
  get '/native/cap/form' => 'native#cap_form', as: 'cap_form'
  get '/native/cap/followup' => 'native#cap_followup', as: 'cap_followup'
  get '/native/cap/followup_invite' => 'native#cap_followup_invite', as: 'cap_followup_invite'
  get '/native/done' => 'native#done', as: 'done'

  #  Mobile native for assessor application

  get '/native/assessor_application/application' => 'native#aa_application', as: 'aa_application'
  get '/native/assessor_application/application_status' => 'native#aa_application_status', as: 'aa_application_status'
  get '/native/assessor_application/qualification' => 'native#aa_qualification', as: 'aa_qualification'
  get '/native/assessor_application/training_time' => 'native#aa_training_time', as: 'aa_training_time'
  get '/native/assessor_application/application_selection' => 'native#aa_application_selection', as: 'aa_application_selection'
  get '/native/assessor_application/validator' => 'native#aa_validator', as: 'aa_validator'
  get '/native/assessor_application/technical_eval' => 'native#aa_technical_eval', as: 'aa_technical_eval'

  # Mobile native for bug reporter
  get '/native/bug-tracker/form' => 'bugs#bug_tracker_form', as: 'bug_tracker_form'
  get '/native/bug-tracker/submitted' => 'bugs#bug_submitted', as: 'bug_submitted'
  # USERS CONTROLLER
  get 'users' => 'users#users', as: 'users'
  get 'users/staff' => 'users#staff', as: 'staff'
  get 'users/email_user' => 'users#email_user', as: 'email_user'
  post 'users/send_email' => 'users#send_email'
  get 'users/new' => 'users#users_new', as: 'users_new'
  get 'users/reset' => 'users#reset'
  get 'users/lock'  => 'users#lock'
  get 'users/unlock'  => 'users#unlock'
  get 'users/invite'  => 'users#invite'
  get 'users/permissions' => 'users#permissions'
  post 'users/permissions' => 'users#post_permissions'
  patch 'users/permissions' => 'users#patch_permissions'
  get 'users/permissions/all' => 'users#permissions_all'
  get 'users/test_login' => 'users#test_login'

  get 'suppliers'          => 'suppliers#suppliers', as: 'suppliers'
  get 'suppliers/:id/edit' => 'suppliers#suppliers_edit', as: 'suppliers_edit'
  get 'suppliers/new'      => 'suppliers#suppliers_new', as: 'suppliers_new'
  post 'add_supplier'      => 'suppliers#supplier_create'

  get 'locked' => 'users#locked', as: 'locked'
  # =====================================================
  # =====================================================

  # REPORTS
  get 'reports' => 'reports#reports', as: 'reports'
  get 'reports/my-reports' => 'reports#my_reports', as: 'my_reports'
  get 'reports/my-reports/:slug' => 'reports#update_report', as: 'update_report'
  get 'reports/my-reports/:slug/ap' => 'reports#update_ap', as: 'update_ap'
  get 'reports/my-reports/:slug/go' => 'reports#update_go', as: 'update_go'
  get 'reports/my-reports/:slug/ca' => 'reports#update_ca', as: 'update_ca'
  get 'reports/my-reports/:slug/cap' => 'reports#update_cap', as: 'update_cap'
  get 'reports/my-reports/:slug/finish' => 'reports#finish_qa', as: 'finish_qa'
  get 'reports/my-reports/:slug/comments' => 'reports#overall_comments', as: 'overall_comments'
  get 'reports/my-reports/:slug/ca/:chapter' => 'reports#update_chapter', as: 'update_chapter'
  get 'reports/my-reports/:slug/dormitory' => 'reports#update_dormitory', as: 'update_dormitory'
  get 'reports/my-reports/:slug/download' => 'reports#download', as: 'download_report'
  get 'reports/my-reports/:slug/download-excel' => 'reports#download_excel', as: 'download_excel'
  get 'reports/my-reports/:slug/download-cap-review' => 'reports#download_cap_review', as: 'download_cap_review'
  get 'reports/my-reports/:slug/upload-cap-revew' => 'reports#upload_cap_review', as: 'upload_cap_review'
  get 'reports/my-reports/:slug/generate-cap-revew' => 'reports#generate_cap_review', as: 'generate_cap_review'
  get 'reports/inprogress' => 'reports#inprogress', as: 'inprogress'
  get 'reports/completed' => 'reports#completed', as: 'completed'
  get 'reports/my-cp-reports/:slug' => 'reports#update_cp_report', as: 'update_cp_report'
  get 'reports/my-cp-reports/:slug/plan-item/:pi_id' => 'reports#update_plan_item', as: 'update_plan_item'
  get 'reports/my-cp-reports/:slug/download' => 'reports#download_cp', as: 'download_cp'

  # CONTROL PLAN
  get 'control-plan' => 'pages#control_plan', as: 'control_plan'
  get 'control-plan/:supplier_code/product-families' => 'control_plans#product_families', as: 'product_families'
  get 'control-plan/:supplier_code/product-families/:pf_id' => 'control_plans#update_product_family', as: 'update_product_family'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps' => 'control_plans#process_steps', as: 'process_steps'
  get 'control-plan/:supplier_code/product-families/:pf_id/process-steps/:ps_id' => 'control_plans#update_process_step', as: 'update_process_step'

  # STATS
  get 'statistics' => 'statistics#statistics', as: 'stats'
  get 'statistics/excel-download' => 'statistics#excel_download', as: 'excel_download'
  get 'statistics/excel/supplier' => 'statistics#excel_by_code', as: 'excel_by_code'
  get 'statistics/excel/global' => 'statistics#excel_global', as: 'excel_global'
  get 'statistics/xuwei' => 'statistics#xuwei_stats'
  get 'statistics/country' => 'statistics#country', as: 'country_stats'
  get 'statistics/process' => 'statistics#industrial_process', as: 'process_stats'
  get 'statistics/result' => 'statistics#result', as: 'result_stats'
  get 'statistics/rank' => 'statistics#rank', as: 'rank_stats'
  get 'statistics/comment' => 'statistics#comment', as: 'comment_stats'
  get 'statistics/supplier' => 'statistics#supplier', as: 'supplier_stats'
  get 'statistics/supplier-full' => 'statistics#supplier_full', as: 'supplier_full_stats'
  get 'statistics/supplier/search' => 'statistics#supplier_search', as: 'supplier_stats_search'
  get 'statistics/supplier/history' => 'statistics#supplier_history', as: 'supplier_history_stats'
  get 'statistics/supplier/:supplier_code' => 'statistics#supplier_qa', as: 'supplier_qa_stats'
  get 'statistics/multiple-stats' => 'statistics#multiple_stats', as: 'multiple_stats'
  get 'statistics/assessment' => 'statistics#assessment', as: 'assessment_stats'

  get 'goes' => 'pages#goes', as: 'goes'

  # GUIDELINES
  get 'guidelines/show' => 'guidelines#show', as: 'guideline'
  get 'guidelines/prep' => 'guidelines#prep', as: 'guideline_prep'
  get 'guidelines/toolbox' => 'guidelines#toolbox', as: 'guideline_toolbox'
  get 'guidelines/frequency' => 'guidelines#frequency', as: 'guideline_frequency'
  post 'guidelines/frequency' => 'guidelines#frequency_update', as: 'create_guideline_frequency'
  post 'guidelines/frequency/:id' => 'guidelines#frequency_update', as: 'update_guideline_frequency'
  resources :guidelines, only: [:index, :edit, :update]

  # CP UPLOADER
  get  'upload-cp' => 'pages#upload_cp', as: 'upload_cp'
  post 'upload-cp' => 'pages#upload_cp', as: 'upload_cp_post'
  put  'upload-cp' => 'pages#upload_cp', as: 'upload_cp_put'

  get  'upload-historical-assessments' => 'pages#upload_historical_assessments', as: 'upload_historical_assessments_path'
  post 'upload-historical-assessments' => 'pages#upload_historical_assessments'
  # # ADMIN
  get 'new-change-log' => 'pages#new_change_log', as: 'change_log'

  get 'login' => 'pages#login', as: 'login'

  # EMAIL SYSTEM
  get 'email-system' => 'emails#email_system', as: 'email_system'
  get 'email-system/send-out' => 'emails#email_send_out', as: 'email_send_out'
  get 'email-system/send-out/new' => 'emails#letter_send_out_new', as: 'letter_send_out_new'
  post 'email-system/send-out/create' => 'emails#letter_send_out_create', as: 'letter_send_out_create'
  get 'email-system/send-out/show/:id' => 'emails#email_send_out_show', as: 'email_send_out_show'

app/models/control_plans/control_plan_helper/reports.rb
module ControlPlanHelper::Reports
  extend ActiveSupport::Concern

  def generate_report
    pdf = PdfGenerator.new(self)
    StringIO.new(pdf.render_pdf)
  end

  def attach_report(file)
    filename = "#{assess_date.strftime('%Y-%m-%d')}-#{supplier_profile.code}-#{supplier_profile.name}-#{grid}.pdf"

    report.attach(
      io: file,
      filename: filename,
      content_type: 'application/pdf'
    )
  end

  def update_report!(_full = true)
    self.report_state = 'PROCESSING'
    save(touch: false)
    file = generate_report
    attach_report(file)
    self.report_state = nil
    self.report_date = Time.now
    save(touch: false)
  rescue StandardError
    puts 'ERROR ENCOUNTERED!!! Resetting report state.'
    self.report_state = nil
    save(touch: false)
  end
end

app/views/reports/_report_row.html.erb
<% qa = report[:object] %>
<% path = update_report_path(slug: qa.slug) if qa.is_a? QualityAssessment %>
<% path = update_cp_report_path(slug: qa.slug) if qa.is_a? ControlPlan %>
<% no_result = qa.is_a?(QualityAssessment) && ([qa.cotation, qa.result].include?(nil)) %>


<tr>
  <th style="<%= 'background-color: yellow;' if no_result %>"><%= report[:code] %></th>
  <td style="<%= 'background-color: yellow;' if no_result %>"><%= report[:supplier] %><br>
    <span style="margin-left: 10px; font-size: 1rem;">By <%= report[:name] %></span>
    <% if no_result %>
    <br><span style="margin-left: 10px; font-size: 1rem; color: red;">Not A Valid Assessment. Assessor chose ALL points as N/A.</span>
    <% end %>
  </td>
  <td style="font-size: 1.1rem; <%= 'background-color: yellow;' if no_result %>"><%= report[:date] %></td>
  <td style="<%= 'background-color: yellow;' if no_result %>"><span class="br-pill" style="color:white;background-color: <%= report[:color] %>; font-size: 1rem;"><%= report[:label] %></span></td>
  <td style="<%= 'background-color: yellow;' if no_result %>">
    <a onclick="getQrcode('<%= report[:id] %>', '<%= report[:type] %>');" class="btn-xs">View on mini program</a>
    <% if !qa.completed %>
    <% elsif no_result %>
    <button onclick="noResult()" class="btn-xs">Generate Report</button>
    <% else %>
    <button onclick="generateReport('<%= path.split('?').first %>', 'PDF', true, true)" class="btn-xs">Generate Report</button>
      <% if qa.cap_close? %>
        <button onclick="generateReport('<%= path.split('?').first %>', 'PDF', true, false )" class="btn-xs">Generate Partial Report</button>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/reports/finish_qa.html.erb
<div class='wrapper' style="margin-bottom: 0.5rem">
  <div style="margin-bottom: 1rem;"><a href="/reports">Reports</a>  <a href="/reports/my-reports">My Reports</a>  › <a href="<%= update_report_path(slug: @qa.slug) %>"><%= @qa.supplier_profile.name %></a> › Finish Assessment</div>
</div>

<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem; border-bottom: 1px solid #C6C0C0; padding-bottom: 1rem;">
  <div class="b">Finish Assessment</div>
</div>

<%= form_with(model: @qa, url: api_v1_data_update_path(name: "quality_assessments", id: @qa.id), method: :post, html: {name: "qa_form"}) do |f| %>
  <!-- Strong Point Textarea -->
  <div style="margin: 1rem 0;">
    <div class="b">Strong Points</div>
    <%= f.text_area :strong_points, style: "height: 5rem;",onfinish:"autoClickForm(event.target.form);", id: "chapter_questions_strong_points" %>
  </div>

  <div style="margin: 1rem 0;">
    <div class="b">Points To Improve</div>
    <%= f.text_area :points_to_improve, style: "height: 5rem;",onfinish:"autoClickForm(event.target.form);", id: "points_to_improve" %>
  </div>

  <div style="margin: 1rem 0;">
    <div class="b">Overall Comments</div>
    <%= f.text_area :overall_comments, style: "height: 5rem;",onfinish:"autoClickForm(event.target.form);", id: "overall_comments" %>
  </div>

 <label for="question">I verify that this assessment is completed.</label>
<br>

<div style="display: flex; align-items: center; margin: 1rem 0;">
  <%= f.check_box :completed, style: "margin-right: 15px;", onchange:"autoClickForm(event.target.form);swal('Assessment Complete!','','success').then(function(){window.history.go(-1); return false;})" %>
  <label>Yes</label>
</div>

<div style="margin: 2rem 0;">
  <%= f.submit "Save Assessment Details", class: "btn-md no-shadow", style: "line-height: 1;" %>
</div>
<% end %>

app/views/reports/my_reports.html.erb
<div class='wrapper' style="margin-bottom: 0.5rem">
  <div style="margin-bottom: 1rem;"><a href="/reports">Reports</a> › My Reports  </div>
</div>

<div class="wrapper">
  <h3>Reports in Progress</h3>
</div>

<div id="table-scroll" class="table-scroll">
  <table id="main-table" class="main-table">
    <thead>
      <tr>
        <th scope="col">Code <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Supplier <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Assessment Type <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Updated at <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Continue Report <span><%= render 'svg/direction' %></span></th>
      </tr>
    </thead>
    <tbody>
      <% @reports.reject{|x| x.completed}.each do |qa| %>
        <% path = update_report_path(slug: qa.slug) if qa.is_a? QualityAssessment %>
        <% path = update_cp_report_path(slug: qa.slug) if qa.is_a? ControlPlan %>
      <tr>
        <th><%= qa.supplier_profile.code %></th>
        <th><%= qa.supplier_profile.name %>
            <br><span style="font-size: 0.8em;">Assessed by <%= qa.assessor_name %></span>
        </th>
        <td><span class="br-pill" style="color:white;background-color:<%= qa.color %>"><%= qa.short_name %> – <%= qa.assess_type %></td>
        <td style="font-size: 1.1rem"><%= qa.updated_at.strftime("%Y-%m-%d") %></td>
        <td>
          <% if current_user.can_edit?(qa) %>
            <%= link_to path do %>
              <button class="btn-xs">Continue reporting</button>
            <% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div style="width: 100%; background: #32A2ED; border-bottom-right-radius:40px; border-bottom-left-radius:40px; color: white;">
  <div style="display: flex; justify-content: space-between; padding: 1rem 1.1rem;">
    <div>Reports in Progress: <strong><%= @reports.reject{|x| x.completed}.count %></strong></div>
    <div></div>
    <div></div>
  </div>
</div>

<div class="wrapper" style="margin-top: 3em">
  <h3>Completed Reports</h3>
</div>


<div id="table-scroll" class="table-scroll">
  <table id="main-table" class="main-table">
    <thead>
      <tr>
        <th scope="col">Code <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Supplier <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Assessment Type <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Updated at <span><%= render 'svg/direction' %></span></th>
        <th scope="col">Actions <span><%= render 'svg/direction' %></span></th>
      </tr>
    </thead>
    <tbody>
      <% @reports.select{|x| x.completed}.each do |qa| %>
      <tr>
        <th><%= qa.supplier_profile.code %></th>
        <th><%= qa.supplier_profile.name %>
          <br><span style="font-size: 0.8em;">Assessed by <%= qa.assessor_name %></span>
        </th>
        <td><span class="br-pill" style="color:white;background-color:<%= qa.color %>"><%= qa.short_name %> – <%= qa.assess_type %></td>
        <td style="font-size: 1.1rem"><%= qa.updated_at.strftime("%Y-%m-%d") %></td>
        <td>
          <% path = update_report_path(slug: qa.slug) if qa.is_a? QualityAssessment %>
          <% path = update_cp_report_path(slug: qa.slug) if qa.is_a? ControlPlan %>

          <% if current_user.can_edit?(qa) %>
          <%= link_to path do %><button class="btn-xs">Edit report</button><% end %>
          <% end %>

          <% if qa.is_a?(QualityAssessment) && ([qa.cotation, qa.result].include?(nil)) %>
            <button onclick="noResult()" class="btn-xs">Generate Report</button>
          <% else %>
            <button onclick="generateReport('<%= path.split('?').first %>', 'PDF', true, true)" class="btn-xs">Generate Report</button>
            <% if qa.cap_close? %>
              <button onclick="generateReport('<%= path.split('?').first %>', 'PDF', true, false )" class="btn-xs">Generate Partial Report</button>
            <% end %>
          <% end %>

          <% if qa.is_a?(QualityAssessment) && !qa.assess_type.include?("CAP") %>
            <%= link_to upload_cap_review_path(slug: qa.slug) do %>
            <button class="btn-xs">Upload CAP Review</button>
            <% end %>
          <% end %>
          <%# if qa.report_date.present? %>
          <!-- <button class="btn-xs white bg-blue">↧ <%#= qa.report_date.strftime("%Y-%m-%d") %> Report</button> -->
          <%# end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <div style="width: 100%; background: #32A2ED; border-bottom-right-radius:40px; border-bottom-left-radius:40px; color: white;">
    <div style="display: flex; justify-content: space-between; padding: 1rem 1.1rem;">
      <div>Completed Reports: <strong><%= @reports.select{|x| x.completed}.count %></strong></div>
      <div></div>
      <div></div>
    </div>
  </div>
<%= javascript_include_tag "table_filter.js" %>
<%= render 'generate_report_js' %>

app/views/reports/update_chapter.html.erb
<div class='wrapper' style="margin-bottom: 0.5rem">
  <div style="margin-bottom: 1rem;">
    <a href="/reports">Reports</a> ›
    <a href="/reports/my-reports">My Reports</a>  ›
    <a href="<%= update_report_path(slug: @qa.slug) %>"><%= @qa.supplier_profile.name %></a> ›
    <a href="<%= update_ca_path(slug: @qa.slug) %>"><%= @qa.short_name %> Chapter Assesments</a> ›
    <% if @qa.dpr? %>
      <%= @gl.sec_name %> <%= @gl.sec_title %>
    <% else %>
      <%= @section.section_name %> <%= @section.title %>
    <% end %>
  </div>
</div>

<div style="margin-bottom: 1rem; border-bottom: 1px solid #C6C0C0; padding-bottom: 1rem;">
  <% if @qa.dpr? %>
  <div class="b"><%= @gl.sec_name %> <%= @gl.sec_title %></div>
  <% else %>
  <div class="b"><%= @section.section_name %> <%= @section.title %></div>
  <div>"<%= @section.content %>"</div>
  <% end %>
</div>

<!-- Letter -->
<div style="display: flex; justify-content: center;">
  <p style="text-align: center; background: white; border-radius: 5px; border: 2px solid #32A2ED; width: 25%; border-bottom: 5px solid #32A2ED">
    <%= @gl_h[:section_name] %>
  </p>
</div>

<% is_cap = @qa.cap? %>

<% @gl_h[:children].each_with_index do |point, i| %>
  <% cq = @cqs.select{|cq| cq.chapter_tag == point[:guideline_tag]}.first %>
  <% next if cq.nil? %>
  <article style="border-bottom: 1px solid rgba(64, 103, 167, 1.00); padding-bottom: 1rem;">
    <!-- Chapter Section Info -->
    <div style="background: rgba(198, 192, 192, 0.5); padding: 1rem; margin: 1rem 0;">
      <% if @qa.dpr? %>
        <% point[:grid_images].each_with_index do |img_src, i| %>
          <div style="position: relative; display: inline-block; width: 200px; height: 200px;margin: 1em 1em 1em 0; vertical-align: middle; background: black; cursor: pointer">
            <img class="hover-fade" src="<%= img_src %>" alt="" height="200px" width="200px" style="object-fit: cover;" onclick="launchLightbox(this)" data-album="<%= point[:grid_images].join(':::') %>">
          </div>
        <% end %>
      <% else %>
      <div class="b"><%= point[:title] %></div>
      <p><%= raw point[:content].split("\n").join('<br>') %></p>
      <p><%= point[:note_header] %></p>
      <ul>
        <% (point[:note_bullets]||[]).each do |bullet| %>
          <li><%= bullet %></li>
        <% end %>
      </ul>
      <% end %>
    </div>

    <% if point[:show_survey] %>
      <div class="b">Current Result: <%= cq.result %></div>
      <div><a class="link" href="<%= update_dormitory_path(slug: @qa.slug) %>">Please complete related question set</a></div>
    <% elsif cq.show_related_assessments? %>
      <% cq.related_assessments_cards.each do |ass| %>
        <%= render 'related_assessment_card', qa: ass, cq: cq %>
      <% end %>
      <%= render 'chapter_question_form', point: point, i: i, cq: cq, is_cap: is_cap, hide_result: cq.related_assessment_id.present? %>
    <% else %>
      <%= render 'chapter_question_form', point: point, i: i, cq: cq, is_cap: is_cap, hide_result: false %>
    <% end %>
  </article>
<% end %>


<div>
  <% if @prev_ca.present? %>
    <%=link_to update_chapter_path(slug: @qa.slug, chapter: @prev_ca.chapter_tag), class: "no-underline" do %>
      <div class="btn-mp-blue" style="margin-top: 20px; margin-right: 10px;">← Prev. Level</div>
    <% end %>
  <% end %>
  <% if @next_ca.present? %>
    <%=link_to update_chapter_path(slug: @qa.slug, chapter: @next_ca.chapter_tag), class: "no-underline" do %>
      <div class="btn-mp-blue" style="margin-top: 20px;">Next Level →</div>
    <% end %>
  <% end %>
</div>

<% if @next_ca.nil? %>
  <%=link_to update_ca_path(slug: @qa.slug), class: "no-underline" do %>
    <div style="display: flex; justify-content: flex-start;">
      <div class="btn-mp-red" style="margin-top: 20px;">Finish This Section</div>
    </div>
  <% end %>
<% end %>



<style>
  .direct-upload {
  display: inline-block;
  position: relative;
  padding: 2px 4px;
  margin: 0 3px 3px 0;
  border: 1px solid rgba(0, 0, 0, 0.3);
  border-radius: 3px;
  font-size: 11px;
  line-height: 13px;
}

.direct-upload--pending {
  opacity: 0.6;
}

.direct-upload__progress {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  opacity: 0.2;
  background: #0076ff;
  transition: width 120ms ease-out, opacity 60ms 60ms ease-in;
  transform: translate3d(0, 0, 0);
}

.direct-upload--complete .direct-upload__progress {
  opacity: 0.4;
}

.direct-upload--error {
  border-color: red;
}

input[type=file][data-direct-upload-url][disabled] {
  display: none;
}
</style>

<script>


  function launchLightbox(e) {

      var album = e.getAttribute("data-album")
      var body = document.querySelector('body')
      var div = document.createElement('div')
      var id = e.getAttribute("data-id")
      div.id = id
      body.appendChild(div)
      console.log(id, 'here')
      console.log(e)
      // console.log(album, '---------------------')
      var res = album.split(":::").map(function(x){return {"src": x , "thumb": x, "subHtml": ''}})
      console.log(res)
      // console.log(res)
      var active = document.getElementById(id)

      lightGallery(active, {
          dynamic: true,
          dynamicEl: res,
          download: false
      })
  }


  function expandDiv(){
    var divs = document.querySelectorAll('#last_attempt_detail');

    divs.forEach(x => {
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    })
  }

  function toggleActionTaken(form, cb){
    var action = form.querySelector('[action_taken]')
    if (cb.value == 'NOK'){
      action.style.display = 'block'
    } else {
      action.style.display = 'none'
    }
  }

</script>